import json
import os

def generate():
    # ES Friend Tasks - Vibe (100)
    es_vibe = [
        "Mira el perfil de redes sociales de {idol_name} y encuentra 3 puntos que han cambiado recientemente. ¡Qué aura!",
        "Intenta recordar la primera impresión que te dio {idol_name}. ¿Cómo ha evolucionado esa vibra?",
        "Busca una frase o mensaje que {idol_name} suela decir y piensa qué significa para ti.",
        "Analiza el estilo de {idol_name} hoy y compáralo con el tuyo. ¿Algún punto en común?",
        "Tómate un tiempo para observar cómo {idol_name} crece en su propio camino (vibe de Madera/Wood).",
        "Elige un momento en el que {idol_name} mostró mucha pasión (Fuego/Fire) y descríbelo.",
        "Checa qué tipo de contenido recomienda {idol_name} y dale una oportunidad a uno.",
        "Busca el logro más reciente de {idol_name} y anota por qué te inspira tanto.",
        "Observa el esfuerzo diario de {idol_name} y compáralo con tu propio ritmo de trabajo.",
        "Analiza la forma de escribir o expresarse de {idol_name} en sus redes... dice mucho de su vibe.",
        "Imagina cómo sería un proyecto ideal liderado por {idol_name} y qué rol jugarías tú.",
        "Elige una foto donde el aura de {idol_name} destaque más y explica por qué te atrapa.",
        "Resume las manías o gestos que {idol_name} repite cuando está con gente.",
        "Encuentra momentos donde la personalidad de {idol_name} (MBTI) se note a leguas.",
        "Lee sobre un reto que {idol_name} superó y aprende de su resiliencia.",
        "Checkea la última actualización de {idol_name} y adivina cómo se siente hoy.",
        "Investiga los gustos actuales de {idol_name}, como comida o hobbies. ¡Puro aesthetic!",
        "Analiza un momento de calma (Agua/Water) de {idol_name} y qué te transmite.",
        "Identifica un punto clave en el éxito de {idol_name} y cómo lo logró.",
        "Arma un pequeño resumen de las etapas por las que ha pasado {idol_name}.",
        "Observa el glow up o cambio de imagen de {idol_name} últimamente.",
        "Analiza los colores o el estilo visual que mejor definen a {idol_name}.",
        "Compara la voz o tono de {idol_name} en diferentes situaciones. ¡Mucha versatilidad!",
        "Encuentra el lado más chill o divertido de {idol_name} en alguna anécdota.",
        "Mira cómo {idol_name} aborda sus proyectos creativos... pura inspiración.",
        "Analiza una colaboración o trabajo en equipo donde {idol_name} brilló.",
        "¿Cuáles son los rasgos de {idol_name} que más admira la gente a su alrededor?",
        "Mira cómo han cambiado los objetivos de {idol_name} con el paso del tiempo.",
        "Checa la creatividad en la forma en que {idol_name} organiza sus ideas.",
        "Identifica 3 palabras que definan la esencia actual de {idol_name}.",
        "Elige un momento con vibra {i_el} de {idol_name} y describe qué sentiste.",
        "Compara las metas antiguas de {idol_name} con los triunfos de hoy.",
        "Observa cómo influye el carácter de {idol_name} en su grupo de amigos o equipo.",
        "Busca una interacción de {idol_name} con alguien que te parezca muy genuina.",
        "Recuerda o busca una situación donde {idol_name} manejó un error de forma pro.",
        "¿Por qué crees que {idol_name} encaja tan bien con cierta vibra o estilo?",
        "Busca el lado más auténtico de {idol_name} en momentos relajados.",
        "Elige el look o estilo que crees que mejor representa a {idol_name}.",
        "Investiga el significado detrás del apodo o nombre que usa {idol_name}.",
        "Observa los momentos de liderazgo o iniciativa de {idol_name}.",
        "Recuerda una vez que la voz o palabras de {idol_name} te sorprendieron gratamente.",
        "Lee sobre una etapa difícil de {idol_name} y cómo la está manejando.",
        "Analiza la amabilidad y el trato de {idol_name} hacia los demás.",
        "Mira qué influencias o personas admira {idol_name} en su vida.",
        "Analiza cómo el aporte de {idol_name} hace que su entorno sea mejor.",
        "Si {idol_name} escribe algo, intenta entender su mundo interior a través de esas líneas.",
        "¿Qué energía elemental crees que define mejor el estilo de {idol_name} hoy?",
        "Observa la dualidad de {idol_name} cuando trabaja vs cuando está de relax.",
        "Compara el inicio de {idol_name} con su nivel actual de confianza.",
        "Mira la rutina o hábitos que {idol_name} sigue para mantenerse al cien.",
        "Busca el gesto o acción de {idol_name} que tenga más energía {i_el}.",
        "Encuentra la conexión entre los sueños de niño de {idol_name} y lo que hace hoy.",
        "Elige una acción muy honesta de {idol_name} y piensa por qué te marcó.",
        "Lee las reflexiones que {idol_name} comparte... pura conexión humana.",
        "Checa cómo celebró {idol_name} su último hito importante.",
        "Identifica el tema que hace que {idol_name} se entusiasme al hablar.",
        "¿Prefieres el lado profesional o el personal de {idol_name}? Decide cuál te gusta más.",
        "Busca un momento de evolución real en la carrera o vida de {idol_name}.",
        "Encuentra elementos en el entorno de {idol_name} que reflejen su energía {i_el}.",
        "Identifica el mensaje principal que {idol_name} transmite a quienes lo rodean.",
        "Busca el reto más difícil que {idol_name} ha aceptado últimamente.",
        "Mira cómo {idol_name} se adapta a situaciones nuevas o desconocidas.",
        "Busca el momento de mayor expresividad de {idol_name} recientemente.",
        "Encuentra una muestra de compañerismo de {idol_name} hacia alguien cercano.",
        "Recuerda una charla con {idol_name} que te haya dejado una buena vibra.",
        "Busca la entrevista o charla donde {idol_name} habló de sus miedos.",
        "Identifica la acción con más energía Madera (Wood) de {idol_name}.",
        "Investiga los próximos planes o metas que {idol_name} tiene en mente.",
        "Elige un momento muy natural y auténtico de {idol_name} en una reunión.",
        "Busca un momento donde {idol_name} mostró una voluntad de hierro (Metal).",
        "Mira el esfuerzo detrás de cámaras que {idol_name} pone en sus proyectos.",
        "Encuentra la etapa donde {idol_name} parecía estar más en su elemento.",
        "Analiza qué dice la forma de ser de {idol_name} sobre su futuro.",
        "Resume cómo se comunica {idol_name} con su círculo cercano.",
        "Elige algo que {idol_name} haya hecho y que quisieras recordar siempre.",
        "Busca el momento donde {idol_name} mostró sus fortalezas con más seguridad.",
        "Encuentra la acción con la energía más intensa y vibrante de {idol_name}.",
        "Compara cómo se describía {idol_name} antes vs cómo lo hace ahora.",
        "Encuentra el cambio más positivo en el camino de crecimiento de {idol_name}.",
        "Observa cómo {idol_name} resolvió un problema de forma elegante.",
        "Si {idol_name} trabaja por su cuenta, mira cómo cambia su vibe al hacerlo.",
        "Identifica la emoción que más transmite {idol_name} al hablar.",
        "Busca el estilo visual o la estética que {idol_name} prefiere en su espacio.",
        "Encuentra la acción con más energía Fuego (Fire) de {idol_name}.",
        "Investiga historias de generosidad o apoyo de {idol_name} hacia otros.",
        "Busca un detalle interesante en el trabajo o proyectos de {idol_name}.",
        "Escucha los consejos o ideas que {idol_name} suele dar.",
        "Nota la diferencia entre el primer proyecto de {idol_name} y el actual.",
        "Busca la habilidad que {idol_name} maneja con más destreza.",
        "Conéctate con un lado más pausado de {idol_name} (vibe de Agua).",
        "Investiga el hábito o rutina más curioso de {idol_name}.",
        "Busca ese momento donde {idol_name} fue un apoyo sólido (Tierra/Earth).",
        "Busca el toque más innovador en los proyectos de {idol_name}.",
        "Identifica el momento más serio y reflexivo de {idol_name}.",
        "Haz un pequeño recuento de los mejores momentos compartidos con {idol_name}.",
        "Resume los ideales que {idol_name} defiende con más pasión.",
        "Analiza cómo se equilibran los 5 elementos en la personalidad de {idol_name}.",
        "Busca algo nuevo que hayas aprendido sobre {idol_name} hoy."
    ]

    # ES Friend Tasks - Heart (100)
    es_heart = [
        "Piensa en el sueño más grande que tiene {idol_name} y compáralo con el tuyo. ¿Alguna conexión?",
        "Anota los momentos en los que {idol_name} se ve más en paz y feliz.",
        "Elige una frase o idea de {idol_name} que te inspire y guárdala para hoy.",
        "Reflexiona sobre una decisión difícil que tomó {idol_name}... ¿qué aprendiste?",
        "Mira cómo ha sido el crecimiento de {idol_name} y escribe tu propia versión.",
        "Aprende de la resiliencia de {idol_name} ante los momentos complicados.",
        "Identifica lo más genuino que has visto en {idol_name} últimamente.",
        "Busca palabras de apoyo que {idol_name} haya dado y llévatelas hoy contigo.",
        "Imagina cómo la vibra de {idol_name} influye positivamente en tu día a día.",
        "Nota en qué aspecto sientes que {idol_name} ha mejorado más como persona.",
        "Describe con tus palabras el valor que {idol_name} aporta a tu vida.",
        "Arma una lista de momentos con {idol_name} para cada mood y explica por qué.",
        "Encuentra esa situación donde {idol_name} fue totalmente transparente.",
        "¿Individual o en grupo? Piensa cuándo brilla más la esencia de {idol_name}.",
        "Imagina cómo armoniza la personalidad de {idol_name} con los 5 elementos.",
        "Busca el lado más real de {idol_name} y por qué se siente tan honesto.",
        "Checa los valores de {idol_name} y ve cómo hacen match con los tuyos.",
        "Observa la confianza sólida (Tierra) que inspira {idol_name}.",
        "Busca el ambiente o mood donde {idol_name} se siente más cómodo.",
        "Anota el gesto más emotivo que {idol_name} ha tenido recientemente.",
        "Conecta con la faceta más introspectiva y profunda de {idol_name}.",
        "Piensa en qué parte de tus sentimientos tocan las palabras de {idol_name}.",
        "Recuerda tu momento más feliz cuando compartiste algo con {idol_name}.",
        "Nota cómo {idol_name} maneja sus puntos débiles y compáralo con tu proceso.",
        "Busca la forma en que {idol_name} ve la amistad o el cariño.",
        "Escribe qué emoción de tu situación actual resuena con {idol_name}.",
        "Describe ese momento donde sentiste que {idol_name} hablaba desde el corazón.",
        "Siente cómo la calma de {idol_name} (Agua) te ayuda a relajarte.",
        "Identifica qué hace único el talento o la forma de ser de {idol_name}.",
        "Anota en qué etapa de tu vida las ideas de {idol_name} te han ayudado más.",
        "Registra la motivación que te da ver el esfuerzo diario de {idol_name}.",
        "Escribe tus sensaciones tras una charla o momento con {idol_name}.",
        "Anota el agradecimiento que sientes hacia {idol_name} por su actitud.",
        "Mira cómo has evolucionado tú mientras apoyabas o veías a {idol_name}.",
        "Encuentra ese momento de honestidad brutal de {idol_name}... es pura fuerza.",
        "Analiza qué relación o recuerdo te trae a la mente {idol_name}.",
        "Elige un rasgo de la determinación de {idol_name} que quieras imitar.",
        "Busca la idea de {idol_name} que mejor describa tu estado de ánimo hoy.",
        "Identifica lo que {idol_name} siempre mantuvo firme y aplícalo a ti.",
        "Piensa en esos ratos de relax total que te da la compañía de {idol_name}.",
        "Busca el tema que más ilumina la cara de {idol_name} al hablar.",
        "Elige la frase que resuma lo mejor de la esencia de {idol_name}.",
        "Imagina qué consejo te daría {idol_name} si estuvieran platicando ahora.",
        "Busca el punto de unión entre tu carácter y la vibra de {idol_name}.",
        "Guarda en tu mente el mensaje más cálido que has recibido de {idol_name}.",
        "Imagina cómo sería tu semana sin las buenas ideas que te da {idol_name}.",
        "Recuerda qué pensabas tú durante el mayor reto de {idol_name}.",
        "Busca un pensamiento positivo sobre el futuro en las palabras de {idol_name}.",
        "Aprende cómo {idol_name} cuida su bienestar y haz algo parecido hoy.",
        "Imagina cómo la energía de {idol_name} equilibra tu propio elemento {u_el}.",
        "Nota cuando {idol_name} acepta sus errores con madurez... ¡ejemplar!",
        "Registra el momento en que un mensaje de {idol_name} te dio más ánimo.",
        "Compara tus aspiraciones actuales con las de {idol_name}.",
        "Conecta un momento de reflexión de {idol_name} con tus propios planes.",
        "Aade un poco de la constancia de {idol_name} a tu daily routine de hoy.",
        "Observa la expresión de satisfacción de {idol_name} al terminar algo bien.",
        "Compara tus gustos en común con {idol_name} y celebra el match.",
        "Comparte con alguien esa idea de {idol_name} que te hizo sonreír hoy.",
        "Encuentra pruebas del crecimiento personal de {idol_name} en este tiempo.",
        "Mira cómo ha cambiado tu forma de ver a {idol_name} con el tiempo.",
        "Busca la reflexión de {idol_name} que te haya puesto a pensar más.",
        "Imagina cómo la vibra elemental de {idol_name} completa la tuya.",
        "Nota si has cambiado algo en ti gracias a la influencia de {idol_name}.",
        "Escribe qué parte de tu personalidad brilla más cuando estás con {idol_name}.",
        "Analiza la respuesta más honesta que {idol_name} ha dado a algo importante.",
        "Escribe en tu diario sobre la pasión (Fuego) que te transmite {idol_name}.",
        "Busca el nuevo comienzo que {idol_name} ha emprendido recientemente.",
        "Anota tus sentimientos de hoy mientras piensas en los consejos de {idol_name}.",
        "Busca lo que {idol_name} más valora de sus amistades o entorno.",
        "Identifica la idea más sabia que has escuchado de {idol_name}.",
        "Mira cómo {idol_name} apoya a los suyos... pura vibra de compañerismo.",
        "Escribe qué dudas se disipan cuando escuchas a o ves a {idol_name}.",
        "Busca el momento en que {idol_name} cumplió un reto personal importante.",
        "Aplica una idea de superación de {idol_name} a tu vida hoy.",
        "Escribe sobre una acción de {idol_name} que te demostró su gran corazón.",
        "Recuerda la primera vez que la forma de ser de {idol_name} te impactó.",
        "Imagina el mensaje de ánimo que {idol_name} te mandaría justo ahora.",
        "Piensa en qué área quieres ser tan firme como la disciplina (Metal) de {idol_name}.",
        "Busca el momento en que {idol_name} cumplió algo que prometió.",
        "Recuerda ese primer instante en que sentiste una conexión real con {idol_name}.",
        "Piensa en la pregunta que más le costó responder a {idol_name}.",
        "Escribe tus sentimientos más honestos (vibe de Agua) inspirados por {idol_name}.",
        "Identifica a quiénes agradece {idol_name} su bienestar actual.",
        "Busca la actividad o hobby de {idol_name} que más te relaja a ti también.",
        "Nota el momento en que {idol_name} habló con más sinceridad de sus planes.",
        "Busca la visión más madura de {idol_name} sobre las relaciones humanas.",
        "Busca un gesto de humildad real de {idol_name} que te haya gustado.",
        "Siente cómo la vibra de {idol_name} ayuda a equilibrar tu energía hoy.",
        "Mira cómo {idol_name} se levantó tras un pequeño tropiezo.",
        "Busca el área donde quieres tener la estabilidad (Tierra) de {idol_name}.",
        "Recuerda cuando {idol_name} se esforzó al máximo por ayudar a otros.",
        "Escribe si alguna idea de {idol_name} cambió tu perspectiva sobre algo.",
        "Elige un hábito positivo de {idol_name} que quieras adoptar hoy mismo.",
        "Identifica qué parte de la energía de {idol_name} resuena más contigo hoy.",
        "Reflexiona sobre lo que {idol_name} hizo para no rendirse nunca.",
        "Escribe qué es lo más valioso que has aprendido de {idol_name}.",
        "Nota qué actividad parece definir mejor la esencia de {idol_name}.",
        "Busca la idea de {idol_name} que mejor sintonice con tu elemento {u_el}.",
        "Conecta un proyecto a futuro de {idol_name} con uno de tus propios sueños.",
        "Imagina la gran sinergia entre tu energía y la de {idol_name} en un diario."
    ]

    # ES Friend Tasks - Energy (100)
    es_energy = [
        "Para activarte, observa el mayor éxito de {idol_name} e intenta aplicar esa energía hoy.",
        "Compara el proceso de crecimiento de {idol_name} con tus propios retos actuales.",
        "Sigue un consejo de productividad de {idol_name} y termina hoy esa tarea pendiente.",
        "Aplica la determinación de {idol_name} a tu objetivo de este día. ¡Hustle!",
        "Contágiate de la energía activa (Fuego) de {idol_name} e inicia algo nuevo hoy.",
        "Prueba el estilo de trabajo que prefiere {idol_name} y ve si te funciona.",
        "Sé disciplinado como el enfoque de {idol_name} y completa hoy un pendiente.",
        "Fluye con la adaptabilidad de {idol_name} (Agua) y maneja los imprevistos de hoy.",
        "Recibe la chispa de inicio (Madera) de {idol_name} y lanza ese pequeño proyecto hoy.",
        "Mira cómo {idol_name} cuida su energía vital y adáptalo a tu rutina diaria.",
        "Organiza tu día de la forma en que {idol_name} suele estructurar sus planes.",
        "Aprende cómo {idol_name} recarga pilas tras un día largo y pruébalo tú.",
        "Elige una cualidad energética de {idol_name} que quieras usar hoy mismo.",
        "Haz un compromiso contigo como la estabilidad de {idol_name} (Tierra) y cúmplelo.",
        "Observa la actitud mental de {idol_name} antes de afrontar un gran cambio.",
        "Mantente activo por 20 min escuchando algo que {idol_name} te haya sugerido.",
        "Nota la dedicación que {idol_name} pone en sus detalles y haz lo mismo hoy.",
        "Absorbe la confianza y el brillo (Fuego) de {idol_name} para tu reunión de hoy.",
        "Usa algo que te recuerde la energía {i_el} de {idol_name} para darte un boost.",
        "Sigue el orden y la disciplina de {idol_name}: haz tu check-list de hoy y cúmplela.",
        "Trabaja en algo importante con el mismo esmero que {idol_name} pone en sus cosas.",
        "Encuentra tu zona de máximo enfoque hoy imitando el estilo de {idol_name}.",
        "Recupera fuerzas con el snack o bebida que {idol_name} prefiere para activarse.",
        "Mueve el cuerpo y estírate siguiendo alguna rutina que {idol_name} mencione.",
        "Prueba la actividad física o deporte que mantiene a {idol_name} con buena vibra.",
        "Con la pasión (Fuego) de {idol_name}, termina hoy esa tarea que tanto te cuesta.",
        "Busca el esfuerzo constante de {idol_name} e imita esa tenacidad hoy mismo.",
        "Camina o mantente en movimiento al ritmo de la energía de {idol_name}.",
        "Aplica un tip de cuidado personal que {idol_name} te haya compartido.",
        "Con la precisión (Metal) de {idol_name}, dale el toque final a un proyecto hoy.",
        "Nota la curiosidad con la que {idol_name} aprende algo y aplícalo a ti hoy.",
        "Dale un refresh a tu espacio de trabajo siguiendo el gusto de {idol_name}.",
        "Aprende cómo {idol_name} maneja la presión y úsalo para calmar tu día.",
        "Sumérgete hoy con todo tu enfoque en una tarea (energía de Agua).",
        "Aplica el profesionalismo que {idol_name} muestra siempre a tu propio día hoy.",
        "Como la energía de inicio (Madera) de {idol_name}, empieza hoy un hábito nuevo.",
        "Si {idol_name} tiene un método para concentrarse, estúdialo y pruébalo ya.",
        "Empieza tu mañana con la mejor actitud, inspirado por la vibra de {idol_name}.",
        "Transmite la buena vibra que te da {idol_name} a alguien de tu entorno hoy.",
        "Sé constante como la firmeza (Tierra) de {idol_name} y repite un acierto hoy.",
        "Mira cómo {idol_name} protege su paz mental de las malas vibras y haz lo mismo.",
        "Observa la dinámica con la que {idol_name} se mueve e intenta activarte más.",
        "Nota cómo {idol_name} entra en 'modo trabajo' y enfócate al máximo hoy.",
        "Mide tu nivel de energía de hoy y compáralo con el empuje de {idol_name}.",
        "Mira el lado más animado de {idol_name} y deja que alegre tu jornada hoy.",
        "Aprende algo nuevo con la curiosidad incansable de {idol_name}.",
        "Si {idol_name} tiene un ritual matutino, adapta una parte a tu propio día.",
        "Siéntete con el valor de afrontar tus retos hoy, como lo hace {idol_name}.",
        "Analiza la postura de {idol_name} ante lo desconocido y cópiala hoy.",
        "Elige algo que te dé energía de tipo {i_el}, como haría {idol_name}.",
        "Encuentra el proyecto que más motiva a {idol_name} y 비교 con tu motor de hoy.",
        "Sal a despejarte un momento siguiendo la recomendación de {idol_name}.",
        "Imita la perseverancia de {idol_name} para mantener su bienestar hoy.",
        "Sé flexible ante los cambios de hoy como la fluidez (Agua) de {idol_name}.",
        "No dejes a medias esa tarea difícil, sigue el ejemplo de aguante de {idol_name}.",
        "Descubre el gusto por aprender hoy con la energía de crecimiento (Madera).",
        "Busca cómo {idol_name} enfoca su fuerza antes de algo clave y úsalo hoy.",
        "Dedica 30 minutos de máximo esfuerzo a tu proyecto, como lo haría {idol_name}.",
        "Comparte algo positivo con alguien hoy, inspirado por el aura de {idol_name}.",
        "Termina tu jornada con orden y limpieza como el cierre (Metal) de {idol_name}.",
        "Mira cómo descansa {idol_name} en su tiempo libre y dqt un respiro tú también.",
        "Mantén tu ritmo y foco hoy con una idea de {idol_name} en la mente.",
        "Usa los puntos fuertes de tu vibra {i_el} hoy de forma consciente como {idol_name}.",
        "Adopta hoy una pizca del estilo enfocado a metas de {idol_name}.",
        "Pon una alarma o recordatorio que te motive, estilo {idol_name}.",
        "Prepara tu compromiso de hoy con el mismo detalle que {idol_name} cuida sus cosas.",
        "Deja que tus ideas fluyan libremente hoy (Agua) como hace {idol_name}.",
        "Busca un ejemplo de seriedad y compromiso de {idol_name} y aplícalo hoy.",
        "Anota tus planes libremente hoy con la creatividad (Madera) de {idol_name}.",
        "Supera el momento más pesado del día recordando el power de {idol_name}.",
        "Averigua qué hace {idol_name} para mantenerse vital y prueba un tip hoy.",
        "Brinda calma a los que te rodean con la estabilidad (Tierra) de {idol_name}.",
        "No sueltes tu objetivo: persiste con la pasión (Fuego) que inspira {idol_name}.",
        "Si {idol_name} usa una frase motivadora, úsala tú también al empezar tu día.",
        "Define tu meta de hoy con claridad, siguiendo la visión de {idol_name}.",
        "Identifica un periodo de gran esfuerzo de {idol_name} y motívate con él.",
        "Actúa con decisión y claridad (Metal) hoy, tal como lo hace {idol_name}.",
        "Encuentra tu propia forma de expresar tu energía, inspirado por {idol_name}.",
        "Imagina el gran impulso que nace al unir tu energía {u_el} con la de {idol_name}.",
        "Si {idol_name} tiene un truco para no distraerse, búscalo y aplícalo hoy mismo.",
        "Analiza el momento de más empuje de {idol_name} y sube tu propio nivel hoy.",
        "Vive este día con plenitud y ganas de crecer (Madera) como {idol_name}.",
        "Nota por qué {idol_name} se entrega al máximo en lo que hace.",
        "Empieza tu día compartiendo una buena noticia o buena vibra tipo {idol_name}.",
        "Mira cómo se cuida {idol_name} cuando siente que sus fuerzas flaquean.",
        "Di algo que anime el ambiente hoy, con la chispa (Fuego) de {idol_name}.",
        "Busca el método de relax de {idol_name} y aplícalo al terminar tus tareas.",
        "Ajusta tu agenda de hoy con la flexibilidad (Agua) que muestra {idol_name}.",
        "Mira cómo superó {idol_name} un momento de mucho cansancio y aprende de ello.",
        "Tómate un descanso real de 15 min hoy para recargar tus vibras como {idol_name}.",
        "Averigua en qué invierte {idol_name} la mayoría de su energía últimamente.",
        "Organiza lo importante y deja lo innecesario (Metal) hoy, igual que {idol_name}.",
        "Mantén tu centro y calma hoy (Tierra) sin importar el ruido externo, como {idol_name}.",
        "Agrega a tu rutina el hábito con el que {idol_name} se renueva cada día.",
        "Visualiza la sinergia ganadora entre tu vibra {u_el} y el estilo de {idol_name}.",
        "Analiza cómo {idol_name} usa su tiempo de forma inteligente para sus logros.",
        "Mira el reto más intenso que {idol_name} ha vencido y supérate tú hoy también."
    ]

    # PT Friend Tasks - Vibe (100)
    pt_vibe = [
        "Dê uma olhada no perfil das redes sociais do {idol_name} e ache 3 pontos que mudaram recentemente. Que aura!",
        "Tente lembrar da primeira impressão que o {idol_name} te passou. Como essa vibe evoluiu?",
        "Procure uma frase ou mensagem que o {idol_name} costuma dizer e pense no que ela significa pra você.",
        "Analise o estilo do {idol_name} hoje e compare com o seu. Algum ponto em comum?",
        "Tire um tempo pra observar como o {idol_name} cresce no próprio caminho (vibe Madeira/Wood).",
        "Escolha um momento em que o {idol_name} mostrou muita paixão (Fogo/Fire) e descreva.",
        "Veja que tipo de conteúdo o {idol_name} recomenda e dê uma chance pra um deles.",
        "Busque a conquista mais recente do {idol_name} e anote por que ela te inspira tanto.",
        "Observe o esforço diário do {idol_name} e compare com o seu próprio ritmo de trabalho.",
        "Analise a forma de escrever ou se expressar do {idol_name} nas redes... diz muito sobre a vibe dele.",
        "Imagine como seria um projeto ideal liderado pelo {idol_name} e que papel você teria.",
        "Escolha uma foto onde a aura do {idol_name} se destaque mais e explique por que ela te prende.",
        "Resuma as manias ou gestos que o {idol_name} repite quando está com as pessoas.",
        "Ache momentos onde a personalidade do {idol_name} (MBTI) fica nítida de longe.",
        "Leia sobre um desafio que o {idol_name} superou e aprenda com a resiliência dele.",
        "Confira a última atualização do {idol_name} e adivinhe como ele está se sentindo hoje.",
        "Pesquise os gostos atuais do {idol_name}, como comida ou hobbies. Puro aesthetic!",
        "Analise um momento de calma (Água/Water) do {idol_name} e o que ele te transmite.",
        "Identifique um ponto chave no sucesso do {idol_name} e como ele chegou lá.",
        "Monte um pequeno resumo das fases pelas quais o {idol_name} já passou.",
        "Observe o glow up ou mudança de visual do {idol_name} ultimamente.",
        "Analise os cores ou o estilo visual que melhor definem o {idol_name}.",
        "Compare a voz ou o tom do {idol_name} em diferentes situações. Muita versatilidade!",
        "Ache o lado mais chill ou divertido do {idol_name} em alguma história engraçada.",
        "Veja como o {idol_name} encara seus projetos criativos... pura inspiração.",
        "Analise uma colaboração ou trabalho em equipe onde o {idol_name} brilhou.",
        "Quais são os traços do {idol_name} que as pessoas ao redor mais admiram?",
        "Veja como os objetivos do {idol_name} mudaram com o passar do tempo.",
        "Confira a criatividade na forma como o {idol_name} organiza as ideias dele.",
        "Identifique 3 palavras que definam a essência atual do {idol_name}.",
        "Escolha um momento com vibe {i_el} do {idol_name} e descreva o que sentiu.",
        "Compare as metas antigas do {idol_name} com os triunfos de hoje.",
        "Observe como o caráter do {idol_name} influencia no seu grupo de amigos ou equipe.",
        "Busque uma interação do {idol_name} com alguém que te pareça muito genuína.",
        "Lembre ou procure uma situação onde o {idol_name} lidou com um erro de forma pro.",
        "Por que você acha que o {idol_name} combina tanto com certa vibe ou estilo?",
        "Busque o lado mais autêntico do {idol_name} em momentos relaxados.",
        "Escolha o look ou estilo que você acha que melhor representa o {idol_name}.",
        "Pesquise o significado por trás do apelido ou nome que o {idol_name} usa.",
        "Observe os momentos de liderança ou iniciativa do {idol_name}.",
        "Lembre de uma vez que a voz ou as palavras do {idol_name} te surpreenderam positivamente.",
        "Leia sobre uma fase difícil do {idol_name} e como ele está lidando com isso.",
        "Analise a gentileza e o trato do {idol_name} com as outras pessoas.",
        "Veja quais influências ou pessoas o {idol_name} admira na vida dele.",
        "Analise como a contribuição do {idol_name} torna o ambiente ao redor melhor.",
        "Se o {idol_name} escrever algo, tente entender o mundo interior dele por essas linhas.",
        "Qual energia elemental você acha que define melhor o estilo do {idol_name} hoje?",
        "Observe a dualidade do {idol_name} quando está trabalhando vs relaxando.",
        "Compare o início do {idol_name} com o nível atual de confiança dele.",
        "Veja a rotina ou os hábitos que o {idol_name} segue pra se manter no topo.",
        "Busque o gesto ou a ação do {idol_name} que tenha mais energia {i_el}.",
        "Ache a conexão entre os sonhos de criança do {idol_name} e o que ele faz hoje.",
        "Escolha uma atitude bem honesta do {idol_name} e pense por que ela te marcou.",
        "Leia as reflexões que o {idol_name} compartilha... pura conexão humana.",
        "Confira como o {idol_name} comemorou sua última conquista importante.",
        "Identifique o assunto que faz o {idol_name} se empolgar ao falar.",
        "Você prefere o lado profissional ou o pessoal do {idol_name}? Decida qual te atrai mais.",
        "Busque um momento de evolução real na carreira ou na vida do {idol_name}.",
        "Ache elementos no ambiente do {idol_name} que reflitam a energia {i_el} dele.",
        "Identifique a mensagem principal que o {idol_name} passa pra quem está por perto.",
        "Busque o desafio mais difícil que o {idol_name} aceitou ultimamente.",
        "Veja como o {idol_name} se adapta a situações novas ou desconhecidas.",
        "Busque o momento de maior expressividade do {idol_name} recentemente.",
        "Ache uma demonstração de parceria do {idol_name} com alguém próximo.",
        "Lembre de um papo com o {idol_name} que tenha te deixado com uma vibe boa.",
        "Busque a entrevista ou conversa onde o {idol_name} falou dos seus medos.",
        "Identifique a ação com mais energia Madeira (Wood) do {idol_name}.",
        "Pesquise os próximos planos ou metas que o {idol_name} tem em mente.",
        "Escolha um momento muito natural e autêntico do {idol_name} numa reunião.",
        "Busque um momento onde o {idol_name} mostrou uma vontade de ferro (Metal).",
        "Veja o esforço nos bastidores que o {idol_name} coloca nos projetos dele.",
        "Ache a fase onde o {idol_name} parecia estar mais no seu elemento.",
        "Analise o que a forma de ser do {idol_name} diz sobre o futuro dele.",
        "Resuma como o {idol_name} se comunica com o seu círculo próximo.",
        "Escolha algo que o {idol_name} tenha feito e que você queira guardar na memória.",
        "Busque o momento onde o {idol_name} mostrou seus pontos fortes com mais segurança.",
        "Ache a ação com a energia mais intensa e vibrante do {idol_name}.",
        "Compare como o {idol_name} se descrevia antes vs como ele faz agora.",
        "Ache a mudança mais positiva no caminho de crescimento do {idol_name}.",
        "Observe como o {idol_name} resolveu um problema de forma elegante.",
        "Se o {idol_name} trabalha por conta própria, veja como a vibe dele muda ao fazer isso.",
        "Identifique a emoção que o {idol_name} mais transmite ao falar.",
        "Busque o estilo visual ou a estética que o {idol_name} prefere no seu espaço.",
        "Ache a ação com mais energia Fogo (Fire) do {idol_name}.",
        "Pesquise histórias de generosidade ou apoio do {idol_name} para os outros.",
        "Busque um detalhe interessante no trabalho ou nos projetos do {idol_name}.",
        "Ouça os conselhos ou ideias que o {idol_name} costuma dar.",
        "Note a diferença entre o primeiro projeto do {idol_name} e o atual.",
        "Busque a habilidade que o {idol_name} domina com mais destreza.",
        "Conecte-se com um lado mais calmo do {idol_name} (vibe de Água).",
        "Pesquise o hábito ou rotina mais curioso do {idol_name}.",
        "Busque aquele momento onde o {idol_name} foi um porto seguro (Terra/Earth).",
        "Busque o toque mais inovador nos projetos do {idol_name}.",
        "Identifique o momento mais sério e reflexivo do {idol_name}.",
        "Faça uma pequena contagem dos melhores momentos compartilhados com o {idol_name}.",
        "Resuma os ideais que o {idol_name} defende com mais paixão.",
        "Analise como se equilibram os 5 elementos na personalidade do {idol_name}.",
        "Busque algo novo que você tenha aprendido sobre o {idol_name} hoje."
    ]

    # PT Friend Tasks - Heart (100)
    pt_heart = [
        "Pense no maior sonho que o {idol_name} tem e compare com o seu. Alguma conexão?",
        "Anote os momentos em que o {idol_name} parece mais em paz e feliz.",
        "Escolha uma frase ou ideia do {idol_name} que te inspire e guarde pra hoje.",
        "Reflexione sobre uma decisão difícil que o {idol_name} tomou... o que aprendeu?",
        "Veja como foi o crescimento do {idol_name} e escreva sua própria versão.",
        "Aprenda com a resiliência do {idol_name} diante dos momentos complicados.",
        "Identifique o que há de mais genuíno que você viu no {idol_name} ultimamente.",
        "Busque palavras de apoio que o {idol_name} tenha dado e leve com você hoje.",
        "Imagine como a vibe do {idol_name} influencia positivamente o seu dia a dia.",
        "Note em que ponto você sente que o {idol_name} mais melhorou como pessoa.",
        "Descreva com suas palavras o valor que o {idol_name} traz para a sua vida.",
        "Monte uma lista de momentos com o {idol_name} para cada mood e explique por quê.",
        "Ache aquela situação onde o {idol_name} foi totalmente transparente.",
        "Individual ou em grupo? Pense quando a essência do {idol_name} brilha mais.",
        "Imagine como a personalidade do {idol_name} harmoniza com os 5 elementos.",
        "Busque o lado mais real do {idol_name} e por que ele soa tão honesto.",
        "Confira os valores do {idol_name} e veja como eles dão match com os seus.",
        "Observe a confiança sólida (Terra) que o {idol_name} inspira.",
        "Busque o ambiente ou mood onde o {idol_name} se sente mais à vontade.",
        "Anote o gesto mais emotivo que o {idol_name} teve recentemente.",
        "Conecte-se com a faceta mais introspectiva e profunda do {idol_name}.",
        "Pense em qual parte dos seus sentimentos as palavras do {idol_name} tocam.",
        "Lembre do seu momento mais feliz quando compartilhou algo com o {idol_name}.",
        "Note como o {idol_name} lida com seus pontos fracos e compare com seu processo.",
        "Busque a forma como o {idol_name} vê a amizade ou o carinho.",
        "Escreva qual emoção da sua situação atual ressoa com o {idol_name}.",
        "Descreva aquele momento onde sentiu que o {idol_name} falava com o coração.",
        "Sinta como a calma do {idol_name} (Água) te ajuda a relaxar.",
        "Identifique o que torna único o talento ou a forma de ser do {idol_name}.",
        "Anote em qual fase da sua vida as ideias do {idol_name} mais te ajudaram.",
        "Registre a motivação que o esforço diário do {idol_name} te proporciona.",
        "Escreva suas sensações após um papo ou momento com o {idol_name}.",
        "Anote a gratidão que você sente pelo {idol_name} e pela atitude dele.",
        "Veja como você também evoluiu enquanto apoiava ou observava o {idol_name}.",
        "Ache aquele momento de honestidade brutal do {idol_name}... é força pura.",
        "Analise qual relação ou lembrança o {idol_name} traz à sua mente.",
        "Escolha um traço da determinação do {idol_name} que você queira imitar.",
        "Busque a ideia do {idol_name} que melhor descreve seu estado de espírito hoje.",
        "Identifique o que o {idol_name} sempre manteve firme e aplique em você.",
        "Pense naqueles momentos de relax total que a companhia do {idol_name} te dá.",
        "Busque o assunto que mais ilumina o rosto do {idol_name} ao falar.",
        "Escolha a frase que resume o melhor da essência do {idol_name}.",
        "Imagine que conselho o {idol_name} te daria se estivessem conversando agora.",
        "Busque o ponto de união entre o seu caráter e a vibe do {idol_name}.",
        "Guarde na memória a mensagem mais calorosa que você recebeu do {idol_name}.",
        "Imagine como seria sua semana sem as boas ideias que o {idol_name} te dá.",
        "Lembre o que você pensava durante o maior desafio do {idol_name}.",
        "Busque um pensamento positivo sobre o futuro nas palavras do {idol_name}.",
        "Aprenda como o {idol_name} cuida do seu bem-estar e faça algo parecido hoje.",
        "Imagine como a energia do {idol_name} equilibra o seu próprio elemento {u_el}.",
        "Note quando o {idol_name} aceita os próprios erros com maturidade... exemplar!",
        "Registre o momento em que uma mensagem do {idol_name} mais te deu ânimo.",
        "Compare suas aspirações atuais com as do {idol_name}.",
        "Conecte um momento de reflexão do {idol_name} com os seus próprios planos.",
        "Adicione um pouco da constância do {idol_name} na sua rotina de hoje.",
        "Observe a expressão de satisfação do {idol_name} ao terminar algo bem feito.",
        "Compare seus gostos em comum com o {idol_name} e celebre o match.",
        "Compartilhe com alguém aquela ideia do {idol_name} que te fez sorrir hoje.",
        "Ache provas do crescimento pessoal do {idol_name} neste tempo.",
        "Veja como sua forma de ver o {idol_name} mudou com o passar do tempo.",
        "Busque a reflexão do {idol_name} que te fez pensar mais profundamente.",
        "Imagine como a vibe elemental do {idol_name} completa a sua.",
        "Note se algo em você mudou graças à influência do {idol_name}.",
        "Escreva qual parte da sua personalidade brilha mais quando está com o {idol_name}.",
        "Analise a resposta mais honesta que o {idol_name} deu sobre algo importante.",
        "Escreva no seu diário sobre a paixão (Fogo) que o {idol_name} te transmite.",
        "Busque o novo recomeço que o {idol_name} encarou recentemente.",
        "Anote seus sentimentos de hoje enquanto pensa nos conselhos do {idol_name}.",
        "Busque o que o {idol_name} mais valoriza nas suas amizades ou no ambiente.",
        "Identifique a ideia mais sábia que você já ouviu do {idol_name}.",
        "Veja como o {idol_name} apoia os seus... pura vibe de parceria.",
        "Escreva quais dúvidas somem quando você ouve ou vê o {idol_name}.",
        "Busque o momento em que o {idol_name} cumpriu um desafio pessoal importante.",
        "Aplique uma ideia de superação do {idol_name} na sua vida hoje.",
        "Escreva sobre uma atitude do {idol_name} que te mostrou o grande coração dele.",
        "Lembre da primeira vez que a forma de ser do {idol_name} te impactou.",
        "Imagine a mensagem de incentivo que o {idol_name} te mandaria agora mesmo.",
        "Pense em qual área você quer ser tão firme quanto a disciplina (Metal) do {idol_name}.",
        "Busque o momento em que o {idol_name} cumpriu algo que prometeu.",
        "Lembre daquele primeiro instante em que sentiu uma conexão real com o {idol_name}.",
        "Pense na pergunta que mais deu trabalho para o {idol_name} responder.",
        "Escreva seus sentimentos mais honestos (vibe de Água) inspirados pelo {idol_name}.",
        "Identifique a quem o {idol_name} agradece pelo seu bem-estar atual.",
        "Busque a atividade ou hobby do {idol_name} que mais te relaxa também.",
        "Note o momento em que o {idol_name} falou com mais sinceridade dos próprios planos.",
        "Busque a visão mais madura do {idol_name} sobre as relações humanas.",
        "Busque um gesto de humildade real do {idol_name} que você tenha curtido.",
        "Sinta como a vibe do {idol_name} ajuda a equilibrar sua energia hoje.",
        "Veja como o {idol_name} deu a volta por cima após um pequeno tropeço.",
        "Busque a área onde você quer ter a estabilidade (Terra) do {idol_name}.",
        "Lembre de quando o {idol_name} se esforçou ao máximo pra ajudar os outros.",
        "Escreva se alguma ideia do {idol_name} mudou sua perspectiva sobre algo.",
        "Escolha um hábito positivo do {idol_name} que você queira adotar hoje mesmo.",
        "Identifique qual parte da energia do {idol_name} ressoa mais com você hoje.",
        "Reflexione sobre o que o {idol_name} fez para nunca desistir.",
        "Escreva o que de mais valioso você aprendeu com o {idol_name}.",
        "Note qual atividade parece definir melhor a essência do {idol_name}.",
        "Busque a ideia do {idol_name} que melhor sintonize com seu elemento {u_el}.",
        "Conecte um projeto futuro do {idol_name} com um dos seus próprios sonhos.",
        "Imagine a grande sinergia entre a sua energia e a do {idol_name} num diário."
    ]

    # PT Friend Tasks - Energy (100)
    pt_energy = [
        "Pra se ativar, observe o maior sucesso do {idol_name} e tente aplicar essa energia hoje.",
        "Compare o processo de crescimento do {idol_name} com seus próprios desafios atuais.",
        "Siga um conselho de produtividade do {idol_name} e termine hoje aquela tarefa pendente.",
        "Aplique a determinação do {idol_name} no seu objetivo deste dia. Corre!",
        "Contagie-se com a energia ativa (Fogo) do {idol_name} e inicie algo novo hoje.",
        "Teste o estilo de trabalho que o {idol_name} prefere e veja se funciona pra você.",
        "Seja disciplinado como o foco do {idol_name} e complete hoje um compromisso pendente.",
        "Flua com a adaptabilidade do {idol_name} (Água) e lide com os imprevistos de hoje.",
        "Receba a centelha inicial (Madeira) do {idol_name} e lance esse pequeno projeto hoje.",
        "Veja como o {idol_name} cuida da sua energia vital e adapte pra sua rotina diária.",
        "Organize seu dia da forma que o {idol_name} costuma estruturar seus planos.",
        "Aprenda como o {idol_name} recarrega as pilhas após um dia longo e teste você também.",
        "Escolha uma qualidade energética do {idol_name} que queira usar hoje mesmo.",
        "Faça um compromisso com você mesmo como a estabilidade do {idol_name} (Terra) e cumpra.",
        "Observe a atitude mental do {idol_name} antes de encarar uma grande mudança.",
        "Mantenha-se ativo por 20 min ouvindo algo que o {idol_name} tenha sugerido.",
        "Note a dedicação que o {idol_name} coloca nos detalhes e faça o mesmo hoje.",
        "Absorva a confiança e o brilho (Fogo) do {idol_name} para a sua reunião de hoje.",
        "Use algo que te lembre a energia {i_el} do {idol_name} pra te dar um boost.",
        "Siga a ordem e a disciplina do {idol_name}: faça sua check-list de hoje e cumpra tudo.",
        "Trabalhe em algo importante com o mesmo capricho que o {idol_name} coloca nas coisas dele.",
        "Ache sua zona de foco máximo hoje imitando o estilo do {idol_name}.",
        "Recupere as forças com o lanche ou bebida que o {idol_name} prefere pra se ativar.",
        "Mexa o corpo e se alongue seguindo alguma rotina que o {idol_name} mencione.",
        "Teste a atividade física ou esporte que mantém o {idol_name} com uma vibe boa.",
        "Com a paixão (Fogo) do {idol_name}, termine hoje aquela tarefa que você tá adiando.",
        "Busque o esforço constante do {idol_name} e imite essa tenacidade hoje mesmo.",
        "Caminhe ou mantenha-se em movimento no ritmo da energia do {idol_name}.",
        "Aplique uma dica de cuidado pessoal que o {idol_name} tenha compartilhado.",
        "Com a precisão (Metal) do {idol_name}, dê o toque final num projeto hoje.",
        "Note a curiosidade com que o {idol_name} aprende algo e aplique em você hoje.",
        "Dê um refresh no seu espaço de trabalho seguindo o gosto do {idol_name}.",
        "Aprenda como o {idol_name} lida com a pressão e use isso pra acalmar o seu dia.",
        "Mergulhe hoje com todo o seu foco numa tarefa (energia de Água).",
        "Aplique o profissionalismo que o {idol_name} sempre mostra no seu próprio dia hoje.",
        "Como a energia de início (Madeira) do {idol_name}, comece hoje um hábito novo.",
        "Se o {idol_name} tem um método de concentração, estude e teste agora mesmo.",
        "Comece sua manhã com a melhor atitude, inspirado pela vibe do {idol_name}.",
        "Transmita a vibe boa que o {idol_name} te dá para alguém do seu lado hoje.",
        "Seja constante como a firmeza (Terra) do {idol_name} e repita um acerto hoje.",
        "Veja como o {idol_name} protege a paz mental dele de vibes ruins e faça o mesmo.",
        "Observe a dinâmica com que o {idol_name} se move e tente se ativar mais.",
        "Note como o {idol_name} entra em 'modo trabalho' e foque ao máximo hoje.",
        "Meça seu nível de energia de hoje e compare com o pique do {idol_name}.",
        "Veja o lado mais animado do {idol_name} e deixe que ele alegre sua jornada hoje.",
        "Aprenda algo novo com a curiosidade incansável do {idol_name}.",
        "Se o {idol_name} tiver um ritual matinal, adapte uma parte pro seu próprio dia.",
        "Sinta-se com coragem para encarar seus desafios hoje, como o {idol_name} faz.",
        "Analise a postura do {idol_name} diante do desconhecido e copie hoje.",
        "Escolha algo que te dê energia do tipo {i_el}, como o {idol_name} faria.",
        "Ache o projeto que mais motiva o {idol_name} e compare com o seu motor de hoje.",
        "Saia pra clarear a mente um pouco seguindo a recomendação do {idol_name}.",
        "Imite a perseverança do {idol_name} pra manter seu bem-estar hoje.",
        "Seja flexível diante das mudanças de hoje como a fluidez (Água) do {idol_name}.",
        "Não deixe pela metade aquela tarefa difícil, siga o exemplo de fôlego do {idol_name}.",
        "Descubra o prazer em aprender hoje com a energia de crescimento (Madeira).",
        "Busque como o {idol_name} foca a força antes de algo chave e use hoje.",
        "Dedique 30 minutos de esforço máximo ao seu projeto, como o {idol_name} faria.",
        "Compartilhe algo positivo com alguém hoje, inspirado pela aura do {idol_name}.",
        "Termine sua jornada com ordem e limpeza como o fechamento (Metal) do {idol_name}.",
        "Veja como o {idol_name} descansa no tempo livre e tire um respiro você também.",
        "Mantenha seu ritmo e foco hoje com uma ideia do {idol_name} na mente.",
        "Use os pontos fortes da sua vibe {i_el} hoje de forma consciente como o {idol_name}.",
        "Adote hoje uma pitada do estilo focado em metas do {idol_name}.",
        "Coloque um alarme ou lembrete que te motive, estilo {idol_name}.",
        "Prepare seu compromisso de hoje com o mesmo detalhe que o {idol_name} cuida das coisas dele.",
        "Deixe suas ideias fluírem livremente hoje (Água) como o {idol_name} faz.",
        "Busque um exemplo de seriedade e compromisso do {idol_name} e aplique hoje.",
        "Anote seus planos livremente hoje com a criatividade (Madeira) do {idol_name}.",
        "Supere o momento mais pesado do dia lembrando do power do {idol_name}.",
        "Descubra o que o {idol_name} faz pra se manter vital e teste uma dica hoje.",
        "Traga calma pra quem está ao seu redor com a estabilidade (Terra) do {idol_name}.",
        "Não solte o seu objetivo: persista com a paixão (Fuego) que o {idol_name} inspira.",
        "Se o {idol_name} usa uma frase motivadora, use você também ao começar seu dia.",
        "Defina sua meta de hoje com clareza, seguindo a visão do {idol_name}.",
        "Identifique um período de grande esforço do {idol_name} e motive-se com ele.",
        "Aja com decisão e clareza (Metal) hoje, tal como o {idol_name} faz.",
        "Ache sua própria forma de expressar sua energia, inspirado pelo {idol_name}.",
        "Imagine o grande impulso que nasce ao unir sua energia {u_el} com a do {idol_name}.",
        "Se o {idol_name} tem um truque pra não se distrair, busque e aplique hoje mesmo.",
        "Analise o momento de mais pique do {idol_name} e suba seu próprio nível hoje.",
        "Viva este dia com plenitude e vontade de crescer (Madeira) como o {idol_name}.",
        "Note por que o {idol_name} se entrega ao máximo no que faz.",
        "Comece seu dia compartilhando uma boa notícia ou vibe boa tipo {idol_name}.",
        "Veja como o {idol_name} se cuida quando sente que as forças estão acabando.",
        "Diga algo que anime o ambiente hoje, com a fagulha (Fogo) do {idol_name}.",
        "Busque o método de relax do {idol_name} e aplique ao terminar suas tarefas.",
        "Ajuste sua agenda de hoje com a flexibilidade (Água) que o {idol_name} mostra.",
        "Veja como o {idol_name} superou um momento de muito cansaço e aprenda com isso.",
        "Tire um descanso real de 15 min hoje pra recarregar suas vibrações como o {idol_name}.",
        "Descubra em que o {idol_name} investe a maior parte da energia ultimamente.",
        "Organize o importante e deixe o desnecessário (Metal) hoje, igual ao {idol_name}.",
        "Mantenha seu centro e calma hoje (Terra) sem ligar pro barulho externo, como o {idol_name}.",
        "Adicione à sua rotina o hábito com que o {idol_name} se renova todo dia.",
        "Visualize a sinergia vencedora entre a sua vibe {u_el} e o estilo do {idol_name}.",
        "Analise como o {idol_name} usa seu tempo de forma inteligente para suas conquistas.",
        "Veja o desafio mais intenso que o {idol_name} venceu e supere-se você também hoje."
    ]

    bundle = {
        "es": {
            "friend_tasks": {
                "vibe": es_vibe,
                "heart": es_heart,
                "energy": es_energy
            }
        },
        "pt": {
            "friend_tasks": {
                "vibe": pt_vibe,
                "heart": pt_heart,
                "energy": pt_energy
            }
        }
    }

    with open('friend_tasks_bundle.json', 'w', encoding='utf-8') as f:
        json.dump(bundle, f, ensure_ascii=False, indent=4)
        print("Generated friend_tasks_bundle.json successfully.")

if __name__ == "__main__":
    generate()
