import json
import os

def generate():
    # Placeholder definitions for reference (not used in strings anymore)
    # idol, i_el, u_el

    # ES Star Tasks - Vibe (98)
    es_vibe = [
        "Búscate el video de debut de {idol} y encuentra 3 cosas que han cambiado... hype total",
        "Grábate haciendo el cover de la performance icónica de {idol}. ¡Pasión > perfección!",
        "Busca esas palabras cute que {idol} le dijo a los fans y siente por qué pegan tan fuerte",
        "Checa los valores de {idol} en una entrevista y haz un mix con los tuyos",
        "Maratón de 1 hora del contenido debut de {idol} para absorber esa energía Wood (木) de puro growth",
        "Elige un stage lleno de la energía Fire (火) de {idol} y escribe qué vibes te dio",
        "Velo por ti mismo: dale una oportunidad a la peli o libro que {idol} recomendó",
        "Elige el momento más top del comeback más reciente de {idol} y anota por qué es tu obsession",
        "Investiga el grind de {idol} en su época trainee y compáralo con tu propio hustle",
        "Analiza la personalidad de {idol} a través de su handwriting en cartas o posts",
        "Imagina el flow del setlist de un concierto de {idol} y el mensaje oculto entre tracks",
        "Elige la foto de photoshoot donde el aura de {idol} brille más y cuéntanos por qué",
        "Resume los catchphrases o rituales que {idol} hace siempre en los fanmeetings",
        "Encuentra 3 momentos de fancams donde el MBTI de {idol} sea literamente real",
        "Lee cómo {idol} superó su época más dark en entrevistas y nánate de esa resiliencia",
        "Checa los últimos posts de Insta o Weverse de {idol} y adivina sus vibes de hoy",
        "Investiga el food aesthetic o los cafés favoritos de {idol}",
        "Analiza un B-side con vibe Water (水) de {idol} línea por línea... lírica profunda",
        "Haz el killing point de la coreo de {idol} y registra esa sensación",
        "Arma un timeline con el evolution de {idol} en cada era o álbum",
        "Resume el glow up del estilo de {idol} desde el debut hasta el worldwide success",
        "Analiza el aesthetic y colores favs de {idol} basado en su contenido",
        "Compara el vocal tone de {idol} en 3 canciones distintas. ¡Versatilidad total!",
        "Encuentra el lado más chill o divertido de {idol} en variedades",
        "Mira cómo cocina su música {idol} en contenido de proceso creativo",
        "Analiza el feat. más épico de {idol} y la nueva faceta que desbloqueó",
        "¿Cuáles son los charming points de {idol} que el fandom no para de biscoitar?",
        "Trackea cómo han evolucionado los goals y sueños de {idol} en el tempo",
        "Checa la creatividad del stage setup y luces en las presentaciones de {idol}",
        "Identifica las 3 palabras que {idol} suelta en cada entrevista... su sello personal",
        "Elige un stage con pura vibra {i_el} de {idol} y describe el feeling",
        "Compara al {idol} que soñaba antes del debut con la estrella de hoy",
        "Mira qué rol juega el MBTI de {idol} en el team chemistry",
        "Busca ese reply de {idol} a un fan que te hizo decir... lo deseo",
        "Encuentra el storytime de un stage blooper contado por {idol}",
        "¿Por qué dicen que {idol} es el king/queen de cierta estación? Analiza su vibe",
        "Busca el raw personality de {idol} en videos de behind the scenes",
        "Elige el outfit de stage que es 100% la esencia de {idol}",
        "Investiga el lore del nombre del fandom de {idol} y por qué les queda de diez",
        "Checa los leadership moments de {idol} en videos o entrevistas",
        "Elige el encore o live improvisado donde la voz de {idol} brilló más",
        "Lee sobre el slump de {idol} y compáralo con sus actividades de esa era",
        "Analiza el fanservice y cartas de {idol}... amor real por el fandom",
        "Checkea el arte o artistas que han influenciado el mundo de {idol}",
        "Analiza cómo el rol de {idol} hace que el grupo brille por completo",
        "Si {idol} escribió lyrics, sumérgete en su inner world a través de ellas",
        "¿Qué elemento del horóscopo chino encaja mejor con el concept del photoshoot de {idol}?",
        "Observa la dualidad de {idol} on-stage vs. off-stage... ¿quién es el real?",
        "Compara el hype del debut de {idol} con su estatus de leyenda actual",
        "Investiga el workout o health routine de {idol} para estar siempre al top",
        "Busca el move de coreo de {idol} con más energía {i_el}",
        "Encuentra el link entre lo que {idol} amaba de niño y sus vibes de hoy",
        "Elige la canción más real y honesta de {idol} y dinos por qué te golpeó",
        "Lee los mensajes de {idol} en el booklet del álbum... pura conexión",
        "Checa el contenido del cumple de {idol} y el festejo más icónico",
        "Identifica el topic que hace que {idol} se ría sin parar en entrevistas",
        "¿Live performance vs MV? Decide cuál versión de {idol} te atrapa más",
        "Busca ese momento donde {idol} fue incomprendido y luego tuvo su re-evolución",
        "Encuentra props o colores en el contenido de {idol} que griten energía {i_el}",
        "Identifica el core message que {idol} siempre repite al fandom",
        "Busca el stage más arriesgado y dark de {idol}",
        "Mira cómo {idol} se adapta a vibes nuevas en otros países",
        "Busca el video con el face expression game más loco de {idol}",
        "Encuentra un momento de cuidado entre miembros (caring moments) iniciado por {idol}",
        "Canta a todo pulmón un track de {idol} que sea perfecto para solistas",
        "Busca la entrevista donde {idol} habla de lo que tuvo que sacrificar",
        "Identifica el performance con más energía Wood (木) de {idol}",
        "Investiga los próximos challenges o metas que {idol} mencionó",
        "Elige el momento más cozy y natural en un fanmeeting game de {idol}",
        "Busca un momento donde {idol} actuó con pura convicción Metal (金)",
        "Velo todo: búscate el behind the scenes del proceso de ensayo de {idol}",
        "Encuentra la era donde {idol} parecía estarse divirtiendo al máximo",
        "Analiza qué dice el signature o caligrafía de {idol} sobre su vibe",
        "Resume cómo es el style de {idol} al comunicarse por social media",
        "Elige el track de {idol} que se quedará en tu playlist forever y cuéntanos por qué",
        "Busca la entrevista donde {idol} presume sus puntos fuertes con orgullo",
        "Encuentra el fancam con la energía más hot y explosiva de {idol}",
        "Compara cómo {idol} se autodefine en diferentes entrevistas de distintas eras",
        "Encuentra el plot twist más dramático en el lore de crecimiento Wood (木) de {idol}",
        "Encuentra el momento donde {idol} salvó un fail en el stage profesionalmente",
        "Si {idol} tiene solo, compáralo con su vibe en el grupo... ¿cambia el mood?",
        "Identifica la palabra de emoción más usada por {idol} en sus entrevistas",
        "Busca el concept visual oculto en el artwork del álbum o MV de {idol}",
        "Encuentra la performance live con más energía Fire (火) de {idol}",
        "Investiga anécdotas de team player de {idol} en el grupo",
        "Descifra el easter egg oculto en el outfit o prop del MV de {idol}",
        "Escucha la playlist o recomendaciones que {idol} hizo para sus fans",
        "Siente el gap entre el primer álbum y el más reciente de {idol}",
        "Busca el skill o talento que {idol} presume con más confidence",
        "Conéctate con un stage chill de {idol} con vibes de Water (水)",
        "Investiga el ritual de fandom más loco o cute de {idol}",
        "Busca ese momento donde {idol} fue el safe place de los fans (Earth energy)",
        "Busca el punto creativo más disruptivo en el stage design de {idol}",
        "Identifica el momento más deep y serio de {idol} en una charla",
        "Crea tu propio anuario con los videos legendarios de {idol} por año",
        "Resume los valores que {idol} siempre intenta pasarle al fandom",
        "Analiza cómo los 5 elementos se mezclan en la discografía de {idol}",
        "Busca algo que no sabías de {idol} y postea tu nuevo descubrimiento"
    ]

    # ES Star Tasks - Heart (100)
    es_heart = [
        "Busca el primer sueño de {idol} de sus entrevistas y compara con el tuyo en tu diario. ¿Match invencible?",
        "Mira el contenido diario de {idol} y anota en qué momentos se siente más chill y relax.",
        "Elige una frase de las lyrics de {idol} que te llegue al cora y ponla de wallpaper hoy.",
        "Checa una decisión icónica de {idol} y piensa qué habrías hecho tú... ¿vibe check?",
        "Busca 3 contenidos que cuenten el growth story de {idol} y arma tu propio timeline.",
        "Mira en entrevistas cómo {idol} aguantó los tiempos difíciles y aplícalo a tu vida.",
        "Elige la frase más honesta de los textos o lyrics de {idol} y dinos por qué rinde rent-free en tu cabeza.",
        "Busca esas palabras de consuelo de {idol} para los fans y elige la que más necesites hoy.",
        "Imagina cómo la energía elemental de {idol} está influenciando tus vibes diarias.",
        "Analiza en qué ha crecido más {idol} desde el debut hasta ahora... su mejor versión.",
        "Define con tus propias palabras qué tipo de artista es {idol} para esta generación.",
        "Arma una playlist con canciones de {idol} para cada estación y explica el feeling.",
        "Busca ese momento en el stage donde {idol} es 100% él/ella mismo/a.",
        "¿Grupo o solo? Compara cuándo brilla más el aura de {idol}.",
        "Imagina cómo el vocal tone de {idol} se conecta con su energía de los 5 elementos.",
        "Busca el contenido donde {idol} se muestra más real y dinos por qué se siente tan sincero.",
        "Checa los valores de {idol} en sus acciones y 비교 con tus propias vibes.",
        "Observa cómo el Earth energy (土) de {idol} crea un lazo de confianza real con el fandom.",
        "Busca el clima o estación fav de {idol} y escucha sus canciones bajo ese mood.",
        "Anota el momento más emocionante que {idol} les ha dado a los fans hasta hoy.",
        "Conecta con la canción de {idol} que tenga las lyrics más deep sobre la soledad.",
        "Piensa qué parte de tu cora tocan esas palabras que {idol} siempre le repite al fandom.",
        "Escucha la música de {idol} y recuerda tu momento más happy ever.",
        "Descubre la debilidad que {idol} intentó superar y compárala con tu propio struggle.",
        "Busca la visión del amor en las lyrics de {idol} y compárala con la tuya.",
        "Escribe qué emoción de tu vida actual representa mejor la música de {idol}.",
        "Describe ese momento en el stage donde sentiste que la emoción de {idol} era 100% real.",
        "Siente cómo la sensibilidad Water (水) de {idol} se filtra en tu propio cora.",
        "Define qué hace a {idol} diferente de otros artistas en su misma posición.",
        "Anota en qué momento exacto de tu vida la música de {idol} encaja mejor.",
        "Registra la inspiración que te da la disciplina y esfuerzo de {idol} en su proceso.",
        "Escribe tus feels después de ver un stage de {idol}... sin filtros, solo fluye.",
        "Anota qué sientes al ver cómo {idol} le da las gracias al fandom de forma tan top.",
        "Busca en qué parte has crecido tú también mientras veías el growth de {idol}.",
        "Busca ese momento donde {idol} mostró su lado más vulnerable... eso es valentía real.",
        "Analiza qué relación de tu vida te recuerda la música de {idol}.",
        "Elige un rasgo de la valentía de {idol} que te gustaría tener tú también.",
        "Busca el verso de las lyrics de {idol} que mejor describa tu situación actual.",
        "Identifica lo que {idol} nunca abandonó y escribe qué es lo que tú no debes soltar.",
        "Piensa en ese momento en el que solo quieres chill y relax con la música de {idol}.",
        "Busca el topic que hace que {idol} se vea más feliz en sus entrevistas.",
        "Elige la frase que resuma los valores core de {idol} y compárala con los tuyos.",
        "Imagina qué te diría {idol} si estuviera a tu lado justo ahora.",
        "Busca qué rasgo de tu personalidad se parece más a la música de {idol}.",
        "Copia en tu diario el mensaje más cálido que {idol} le ha dedicado al fandom.",
        "Imagina cómo sería tu daily routine si no existiera la música de {idol}.",
        "Recuerda qué estabas haciendo tú en la época más difícil de {idol}.",
        "Busca un mensaje positivo sobre el futuro en las lyrics de {idol} y guárdalo hoy.",
        "Aprende cómo {idol} protege su propia energía y aplícalo a ti.",
        "Imagina cómo la música de {idol} resuena con tu elemento {u_el}.",
        "Busca el momento donde {idol} aceptó sus propias imperfecciones... ¡brutal!",
        "Registra el momento exacto en el que la música de {idol} te dio más consuelo.",
        "Busca en qué se parecen tus sueños a los sueños que tiene {idol}.",
        "Conecta una canción de soledad o nostalgia de {idol} con tus propios feels.",
        "Añade un toque de la disciplina de {idol} a tu propia daily routine hoy.",
        "Observa la expresión de {idol} justo cuando termina un stage... pura emoción.",
        "Compara tus likes y dislikes con los de {idol} y busca el match.",
        "Mándale a un amigo esa frase de las lyrics de {idol} que te hizo click total.",
        "Busca pruebas de que {idol} ya no es solo un idol, sino un artista de verdad.",
        "Mira cómo han evolucionado tus sentimientos como fan de {idol} en el tempo.",
        "Busca la frase de {idol} que te ha dejado pensando más profundamente.",
        "Imagina cómo la energía elemental de {idol} llena los huecos de la tuya.",
        "Registra si has hecho algo creativo inspirado por el arte de {idol}.",
        "Escribe qué parte de tu forma de ser sale a relucir cuando escuchas a {idol}.",
        "Busca la pregunta de entrevista que {idol} respondió con más cuidado.",
        "Escribe un diario sobre la motivación que te da la energía Fire (火) de {idol}.",
        "Busca el nuevo challenge que {idol} empezó con su energía Wood (木).",
        "Escribe tus feels de hoy en un diario mientras escuchas a {idol}.",
        "Busca lo que {idol} dijo que más espera de sus fans en el futuro.",
        "Busca la frase más sabia de las lyrics escritas por {idol}.",
        "Busca videos donde {idol} cuida a los otros miembros del grupo... caring vibes.",
        "Escribe qué ansiedades se calman cuando le das al play a {idol}.",
        "Busca el momento en que {idol} cumplió una promesa que se hizo a sí mismo.",
        "Aplica un mensaje de cambio y challenge de {idol} a tu propia vida hoy.",
        "Escribe sobre la acción de {idol} que te demostró su sinceridad total.",
        "Recuerda y escribe la emoción que sentiste la primera vez que escuchaste a {idol}.",
        "Imagina el consejo que {idol} te daría hoy y escríbelo en tu diario.",
        "Busca en qué área de tu vida quieres ser firme como el Metal (金) de {idol}.",
        "Busca el momento en que {idol} cumplió una promesa hecha a los fans.",
        "Recuerda ese primer momento en que la música de {idol} te emocionó de verdad.",
        "Busca la pregunta de entrevista que {idol} tardó más en responder.",
        "Escribe tus sentimientos más profundos y honestos (Water vibe) en tu diario hoy.",
        "Busca la entrevista donde {idol} menciona a las personas a las que está agradecido.",
        "Identifica el instrumento o melodía en la música de {idol} que más te calma.",
        "Busca la entrevista donde {idol} habla con más honestidad sobre sus sueños.",
        "Busca la canción con la visión más madura sobre el amor de toda la discografía de {idol}.",
        "Busca el momento en que {idol} actuó con más humildad y respeto.",
        "Siente cómo la música de {idol} rellena tu energía elemental faltante.",
        "Busca cómo {idol} se recuperó después de un fallo o una decepción.",
        "Busca el área de tu vida donde quieres avanzar con paso firme (Earth energy) como {idol}.",
        "Recuerda el momento en que {idol} se entregó al 100% por sus fans.",
        "Escribe si hay alguna canción de {idol} que marcara un antes y un después en tu vida.",
        "Elige un rasgo de la actitud ante la vida de {idol} que te encantaría copiar.",
        "Busca el track que más resuena con tu propia vibra energética justo ahora.",
        "Busca la razón por la que {idol} pudo aguantar cuando las cosas se pusieron feas.",
        "Escribe lo más valioso que has aprendido viendo el growth de {idol}.",
        "Averigua cuál es la canción que {idol} siente que lo define mejor y anótalo.",
        "Busca la frase de las lyrics de {idol} que haga sintonía con tu elemento {u_el}.",
        "Busca el sueño que {idol} quiere cumplir algún día y conéctalo con el tuyo.",
        "Imagina cómo tu energía y la de {idol} se complementan... escríbelo en tu diario."
    ]

    # ES Star Tasks - Energy (97)
    es_energy = [
        "Para sentir la energía de {idol}, mira su mejor performance y anota qué momento brilló más. ¡Puro aura!",
        "Busca el growth story de {idol} y compáralo con tu propio timeline de crecimiento.",
        "Escucha la música que {idol} recomendó y termina hoy esa tarea que tenías pendiente. ¡Hustle real!",
        "Busca la parte del growth story de {idol} que más te identifique y aplícala a tu reto de hoy.",
        "Empápate de la Fire energy (火) de {idol} e intenta algo nuevo hoy. ¡Atrévete!",
        "Escucha el género de música que {idol} ama y descubre qué parte hace click contigo.",
        "Sé firme como el Metal (金) de {idol} y termina hoy algo a la perfección.",
        "Fluye como el Water energy (水) de {idol} y escribe tus feelings honestos en tu diario hoy.",
        "Recibe la Wood growth energy (木) de {idol} y empieza ese nuevo hobby o reto hoy mismo.",
        "Busca cómo {idol} cuida su condición física y adáptalo a tu rutina. ¡Health is wealth!",
        "Crea tu propio setlist ideal para un concierto de {idol} y explica tus elecciones.",
        "Aprende cómo {idol} superó su slump y compáralo con tu forma de manejar el estrés.",
        "Elige el rasgo de energía de {idol} que más quieras copiar y ponlo en práctica hoy.",
        "Haz una pequeña promesa contigo mismo hoy como el Earth energy (土) de {idol} y cúmplela.",
        "Busca qué mindset tenía {idol} antes de un gran reto en sus entrevistas.",
        "Sal a caminar o haz ejercicio ligero por 30 min escuchando el flow de {idol}.",
        "Busca cómo {idol} practicaba una y otra vez para el stage y aplícalo a tu grind de hoy.",
        "Absorbe el carisma Fire (火) de {idol} y actúa con total confianza hoy.",
        "Usa un accesorio del color de la energía {i_el} de {idol} hoy para atraer buenas vibes.",
        "Sigue el ejemplo de disciplina de {idol}: haz un plan para hoy y cúmplelo a rajatabla.",
        "Prepara algo importante hoy con el mismo detalle que {idol} prepara un stage.",
        "Trabaja hoy con máxima concentración usando la música de {idol} como BGM.",
        "Recarga pilas con la comida o snack favorito que siempre menciona {idol}.",
        "Mueve el cuerpo siguiendo los pasos de la coreo de {idol}... úsalo como stretching.",
        "Prueba el deporte o actividad física que {idol} disfruta para activarte.",
        "Con la pasión Fire (火) de {idol}, dalo todo hoy en una sola tarea importante.",
        "Busca lo que {idol} repitió mil veces para lograr su goal y haz lo mismo hoy.",
        "Camina o corre al ritmo del track más movido de {idol}.",
        "Prueba uno de los tips de self-care que {idol} les recomendó a los fans.",
        "Con la precisión Metal (金) de {idol}, termina algo hoy con un acabado de diez.",
        "Observa la actitud de {idol} cuando aprende algo nuevo e imítala.",
        "Pon el track más rápido de {idol} y dale un glow up a tu cuarto limpiando todo.",
        "Busca cómo {idol} se quita el estrés y aplícalo a tu día hoy.",
        "Sumérgete en algo profundamente hoy con la energía Water (水) de {idol}.",
        "Aplica el pro-spirit que {idol} muestra en el set de grabación a tu propio trabajo hoy.",
        "Como la Wood energy (木) de {idol}, empieza algo hoy por primera vez. ¡Fresh start!",
        "Si {idol} tiene una rutina para enfocarse, búscala y pruébala hoy.",
        "Empieza tu mañana con el vibe a tope escuchando tu canción fav de {idol}.",
        "Pasa la energía positiva que {idol} le da a los fans a alguien de tu entorno hoy.",
        "Sé constante como la Earth energy (土) de {idol} y repite un hábito hoy sin fallar.",
        "Averigua cómo {idol} se protege del hate y aplícalo para cuidar tu paz mental.",
        "Mira el performance más dinámico de {idol} y mueve el cuerpo tú también.",
        "Mira cómo {idol} entra en la zona y concéntrate totalmente en una cosa hoy.",
        "Evalúa tu nivel de energía hoy del 1 al 10 mientras escuchas a {idol}.",
        "Mira el contenido más alegre de {idol} y deja que esa vibra ilumine tu día.",
        "Disfruta aprendiendo algo hoy con la pasión Fire (火) de {idol}.",
        "Si {idol} tiene un ritual antes de salir al stage, adáptalo a tu rutina de inicio.",
        "Dale play al track más valiente de {idol} y saca fuerzas para el día.",
        "Busca qué actitud tiene {idol} cuando se enfrenta a algo que no domina.",
        "Come algo que represente la energía {i_el} de {idol} para recargar tu aura.",
        "Busca el proyecto en el que {idol} más se enfocó y 비교 con tu propio goal.",
        "Sal a dar un paseo o una vuelta escuchando el flow of {idol}.",
        "Intenta imitar el esfuerzo que hace {idol} para mantener su condición física.",
        "Adáptate a los cambios hoy con la fluidez Water (水) de {idol}.",
        "No te rindas en esa tarea difícil de hoy, igual que {idol} no se rindió con su coreo.",
        "Siente el placer de aprender algo nuevo con la Wood energy (木) de {idol}.",
        "Busca cómo {idol} enfoca su energía antes de un show y aplícalo antes de algo importante.",
        "Pon el track más motivador de {idol} y dalo todo durante 30 minutos.",
        "Pasa la buena vibra que recibiste de {idol} diciendo algo positivo a alguien hoy.",
        "Termina tu día de forma limpia y ordenada como la energía Metal (金) de {idol}.",
        "Busca cómo {idol} recarga pilas en su día libre y adáptalo a ti.",
        "Mantén tu flow y concentración hoy con la música de {idol} de fondo.",
        "Usa los puntos fuertes de tu energía {i_el} hoy de forma consciente como {idol}.",
        "Aplica hoy algo del goal-oriented style de vida que lleva {idol}.",
        "Usa la canción más hype de {idol} como tu alarma de despertar hoy.",
        "Prepara tu cita o compromiso de hoy con el mismo esmero que {idol} se prepara para los fans.",
        "Deja que tus emociones fluyan suavemente hoy como el Water energy (水) de {idol}.",
        "Busca un ejemplo de profesionalidad total de {idol} ante cualquier situación.",
        "Anota tus ideas libremente hoy con la inspiración Wood (木) de {idol}.",
        "Aguanta el momento más difícil del día escuchando el power de {idol}.",
        "Busca el secreto de {idol} para mantener su vitalidad según sus entrevistas.",
        "Dale estabilidad a los que te rodean hoy como el Earth energy (土) de {idol}.",
        "No sueltes lo que querías dejar: termina esa tarea con el Fire energy (火) de {idol}.",
        "Si {idol} se dice algo a sí mismo antes de empezar, úsalo tú también hoy.",
        "Define tu meta de hoy en una sola frase escuchando a {idol}.",
        "Busca el periodo en que {idol} trabajó sin parar y enfócate tú también esta semana.",
        "Habla y actúa con precisión hoy como el Metal energy (金) de {idol}.",
        "Busca cómo {idol} expresa su energía y encuentra tu propia forma de expresarte.",
        "Imagina el power que surge cuando tu energía {u_el} se junta con el {i_el} de {idol}.",
        "Si {idol} tiene un truco para cuando se distrae, búscalo y úsalo hoy.",
        "Checa el performance con más power de {idol} y evalúa tu propio nivel de energía.",
        "Vive hoy con la máxima vitalidad siguiendo la Wood energy (木) de {idol}.",
        "Busca por qué {idol} no se guarda nada de energía cuando está en el stage.",
        "Pon el track con más vibe de energía como tu primera canción del día.",
        "Busca cómo se cuida {idol} cuando su energía está al mínimo.",
        "Di algo que alegre el ambiente a tu alrededor con la Fire energy (火) de {idol}.",
        "Busca el recovery method de {idol} post-concierto y aplícalo a tu descanso.",
        "Ajusta tus planes hoy con la flexibilidad de la Water energy (水) de {idol}.",
        "Busca cómo superó {idol} un momento de cansancio extremo.",
        "Descansa 30 min totalmente escuchando a {idol} para recargar tu aura.",
        "Averigua en qué actividad {idol} puso más energía de toda su carrera.",
        "Limpia lo que no sirva y quédate con lo importante hoy como el Metal energy (金) de {idol}.",
        "Mantén tu propio ritmo hoy sin perder el centro como el Earth energy (土) de {idol}.",
        "Añade a tu rutina la forma en que {idol} obtiene nueva energía cada día.",
        "Imagina la sinergia brutal entre tu energía {u_el} y el {i_el} de {idol}.",
        "Analiza cómo {idol} usa su energía de forma eficiente durante la promo.",
        "Mira el stage más intenso de {idol} y sube un nivel tu propia vitalidad hoy."
    ]

    # PT Star Tasks - Vibe (98)
    pt_vibe = [
        "Assista ao vídeo de debut do {idol} e ache 3 coisas que mudaram pra krl até hoje. Hype real!",
        "Tente fazer o cover da performance mais icônica do {idol} e grave. O que vale é o corre, não a perfeição!",
        "Procure as palavras fofas que o {idol} mandou pros fãs e sinta por que elas batem tão forte.",
        "Veja os valores do {idol} em uma entrevista e faça um mix com a sua própria visão.",
        "Maratona de 1 hora de conteúdo de debut do {idol} pra sentir a energia Wood (木) de puro growth.",
        "Escolha um stage com a vibe Fire (火) do {idol} e escreva o que você sentiu no momento.",
        "Veja você mesmo: dê uma chance pro filme ou livro que o {idol} recomendou pro fandom.",
        "Ache o momento mais top do comeback recente do {idol} e anote por que virou sua nova obsessão.",
        "Investigue o grind do {idol} na época de trainee e compare com o seu próprio trampo.",
        "Analise a personalidade do {idol} através do handwriting dele em cartas ou posts.",
        "Imagine a ordem das tracks num setlist de show do {idol} e o significado por trás do flow.",
        "Escolha a foto de photoshoot onde a vibe do {idol} mais brilha e anote o motivo.",
        "Resuma os bordões ou manias que o {idol} sempre faz nos fanmeetings.",
        "Ache 3 momentos em fancams onde o MBTI do {idol} fica simplesmente óbvio demais.",
        "Leia sobre como o {idol} superou os momentos difíceis e se inspire nessa resiliência.",
        "Confira os últimos posts no Insta ou Weverse do {idol} e tente adivinhar o mood dele hoje.",
        "Pesquise as comidas favs ou o estilo de café que o {idol} frequenta. Puro aesthetic!",
        "Analise um B-side com vibe Water (水) do {idol} linha por linha... lírica pesada.",
        "Tente fazer o killing point da coreo do {idol} e registre essa sensação de hit!",
        "Faça uma timeline com a evolução do {idol} em cada era ou álbum novo.",
        "Resuma o glow up do estilo do {idol} do debut até virar ícone mundial.",
        "Analise as cores e o aesthetic fav do {idol} baseado em entrevistas ou conteúdo.",
        "Compare como o tom de voz do {idol} muda em 3 músicas diferentes. Versatilidade é tudo!",
        "Descubra o lado mais chill ou engraçado do {idol} em programas de variedades.",
        "Veja como o {idol} cria suas músicas em conteúdos de processo criativo. Puro trampo!",
        "Analise o feat mais épico do {idol} e a nova faceta que ele desbloqueou nas parcerias.",
        "Quais os charming points do {idol} que o fandom simplesmente não para de biscoitar?",
        "Acompanhe como os sonhos e metas do {idol} evoluíram ao longo do tempo.",
        "Ache la criatividade no stage design e jogo de luzes nas performances do {idol}.",
        "Identifique as 3 palavras ou expressões que o {idol} solta em cada entrevista.",
        "Escolha uma performance que passe a vibe {i_el} do {idol} e descreva esse feeling.",
        "Compare o {idol} que sonhava antes do debut com a estrela que ele é hoje.",
        "Observe como o MBTI do {idol} influencia no group dynamic e no team spirit.",
        "Ache aquele reply direto do {idol} pra um fã que te fez dizer: ídolo real!",
        "Descubra a história de algum stage blooper (erro) contado pelo próprio {idol}.",
        "Por que os fãs dizem que certa estação ou clima combina 100% com o {idol}?",
        "Veja a raw personality do {idol} em vídeos de behind the scenes das gravações.",
        "Escolha o outfit de stage que você acha que é a cara do {idol} de verdade.",
        "Pesquise o lore por trás do nome do fandom do {idol} e por que ele encaixa tão bem.",
        "Veja os momentos de leadership do {idol} em vídeos ou entrevistas. Postura de líder!",
        "Ache o encore ou live improvisado onde a voz do {idol} brilhou ainda mais.",
        "Leia sobre o slump do {idol} e compare com as atividades dele naquela época.",
        "Analise o fanservice e cartas do {idol}... puro amor de verdade pelo fandom.",
        "Ache o artista ou obra que o {idol} citou como influência no seu trampo.",
        "Analise como a posição do {idol} faz o grupo brilhar por completo no palco.",
        "Se o {idol} escreveu alguma letra, mergulhe no mundo interior dele através delas.",
        "Qual energia dos 5 elementos combina melhor com o concept do photoshoot do {idol}?",
        "Observe a dualidade do {idol} no palco vs fora dele... quem é o verdadeiro?",
        "Compare o hype inicial do debut do {idol} con o status de lenda que ele tem agora.",
        "Investigue a rotina de treino ou saúde do {idol} pra estar sempre no topo.",
        "Ache o passo de dança do {idol} que mais passa a vibe da energia {i_el}.",
        "Ache a conexão entre o que o {idol} amava quando criança e os gostos de hoje.",
        "Escolha a track do {idol} que tem as letras mais honestas e diga por que te tocou.",
        "Leia as mensagens que o {idol} deixou no encarte do álbum... pura conexão real.",
        "Veja o conteúdo de aniversário do {idol} e o jeito mais icônico que ele comemorou.",
        "Descubra qual assunto faz o {idol} rir de verdade em todas as entrevistas.",
        "Live performance vs MV? Escolha qual versão do {idol} te prende mais.",
        "Ache aquele momento onde o {idol} foi mal interpretado e depois teve seu comeback moral.",
        "Ache props ou cores no conteúdo do {idol} que gritem a energia de {i_el}.",
        "Identifique a mensagem core que o {idol} sempre reforça para o fandom.",
        "Ache a performance mais experimental e dark da carreira do {idol}.",
        "Veja como o {idol} se adapta a novas culturas quando viaja pro exterior.",
        "Busca o vídeo com o face expression game mais insano do {idol}.",
        "Ache um momento de parceria e cuidado entre os membros iniciado pelo {idol}.",
        "Cante bem alto aquela música do {idol} que é perfeita pra um solo de chuveiro.",
        "Ache a entrevista onde o {idol} fala sobre as coisas que teve que abrir mão.",
        "Escolha a performance com a energia Wood (木) mais forte do {idol}.",
        "Descubra os próximos desafios ou metas que o {idol} mencionou recentemente.",
        "Escolha o momento mais comfy e natural de um fanmeeting game do {idol}.",
        "Busca um momento onde o {idol} agiu com a convicção forte da energia Metal (金).",
        "Veja tudo: busque o behind the scenes do processo de ensaio pesado do {idol}.",
        "Ache a era em que o {idol} parecia estar aproveitando cada segundo no palco.",
        "Analise o que a assinatura ou letra do {idol} revela sobre a vibe dele.",
        "Resuma o estilo de comunicação do {idol} no social media. Ele é do tipo que interage?",
        "Escolha a track do {idol} que vai ficar na sua playlist pra sempre e diga o motivo.",
        "Ache la entrevista onde o {idol} fala dos seus pontos fortes com maior orgulho.",
        "Ache a fancam onde a energia do {idol} está mais hot e explosiva. Lacrou!",
        "Compare como o {idol} se define em entrevistas de diferentes eras da carreira.",
        "Ache a reviravolta mais dramática no lore de crescimento Wood (木) do {idol}.",
        "Ache o momento onde o {idol} contornou um fail no palco de forma super profissional.",
        "Se o {idol} tem carreira solo, compare com a vibe dele no grupo... muda muito?",
        "Identifique a palavra de emoção que o {idol} mais solta em suas entrevistas.",
        "Analise o conceito visual oculto na artwork do álbum ou no MV do {idol}.",
        "Ache a performance live com a energia Fire (火) mais intensa do {idol}.",
        "Investigue as histórias de companheirismo e trabalho em equipe do {idol}.",
        "Descubra o easter egg escondido no outfit ou no cenário do MV do {idol}.",
        "Ouça a playlist ou as dicas de músicas que o {idol} indicou pros fãs.",
        "Sinta a diferença de vibe entre o primeiro álbum e o hit mais recente do {idol}.",
        "Ache o skill o talento que o {idol} ostenta com mais confiança e brilho.",
        "Conecte-se com um stage mais chill do {idol} com vibe da energia Water (水).",
        "Pesquise a tradição ou ritual de fandom mais único do {idol}.",
        "Ache aquele momento onde o {idol} foi o safe place pros fãs (energia Earth).",
        "Ache o ponto de criatividade mais disruptivo no stage design do {idol}.",
        "Identifique o momento mais deep e sério do {idol} en uma conversa real.",
        "Crie seu próprio anuário com vídeos lendários do {idol} separados por ano.",
        "Resuma os ideais que o {idol} sempre tenta passar pra quem o acompanha.",
        "Analise como os 5 elementos se misturam na vibe da discografia do {idol}.",
        "Ache algo que você não sabia sobre o {idol} e anote essa nova descoberta."
    ]

    # PT Star Tasks - Heart (100)
    pt_heart = [
        "Se for difícil falar, mande uma mensagem pro {idol} com uma frase bem sincera. Abre o cora!",
        "Repare no conteúdo diário do {idol} e anote em quais momentos ele parece mais chill e relax.",
        "Escolha uma frase das lyrics do {idol} que bateu forte e coloque como wallpaper hoje.",
        "Veja uma decisão icônica que o {idol} tomou e pense: o que eu faria no lugar dele? Vibe check!",
        "Ache 3 conteúdos que mostrem a growth story do {idol} e monte sua própria timeline.",
        "Veja em entrevistas como o {idol} segurou a barra nos tempos difíceis e aplique isso na sua vida.",
        "Escolha a frase mais honesta das lyrics do {idol} e diga por que ela não sai da sua cabeça.",
        "Busque as palavras de conforto que o {idol} mandou pros fãs e escolha a que você mais precisa hoje.",
        "Imagine como a energia elemental do {idol} está influenciando suas vibrações diárias.",
        "Analise em que o {idol} mais cresceu desde o debut até hoje... a sua melhor versão.",
        "Defina com suas próprias palavras que tipo de artista o {idol} é para essa geração.",
        "Monte uma playlist com músicas do {idol} para cada estação e explique o feeling de cada uma.",
        "Ache aquele momento no stage onde o {idol} é 100% ele mesmo, sem filtros.",
        "Grupo ou solo? Compare quando a aura do {idol} brilha com mais intensidade.",
        "Imagine como o vocal tone do {idol} se conecta com a energia dos 5 elementos.",
        "Ache o conteúdo onde o {idol} se mostra mais real e diga por que sentiu verdade ali.",
        "Veja os valores do {idol} nas ações dele e faça um mix com as suas próprias vibes.",
        "Observe como a energia Earth (土) do {idol} cria um laço de confiança real com os fãs.",
        "Ache o clima ou estação fav do {idol} e ouça as músicas dele sob esse mood.",
        "Anote o momento mais emocionante que o {idol} já proporcionou pro fandom até hoje.",
        "Conecte-se com a música do {idol} que tenha as letras mais deep sobre solidão.",
        "Pense em qual parte do seu cora batem as palavras que o {idol} sempre repete pros fãs.",
        "Ouça a música do {idol} e lembre do seu momento mais happy ever de todos.",
        "Descubra a fraqueza que o {idol} tentou superar e compare com o seu próprio corre.",
        "Busque a visão sobre o amor nas lyrics do {idol} e compare com a sua visão.",
        "Escreva qual emoção da sua vida hoje a música do {idol} representa melhor.",
        "Descreva aquele momento no stage onde você sentiu que a emoção do {idol} era 100% real.",
        "Sinta como a sensibilidade Water (水) do {idol} se infiltra no seu próprio coração.",
        "Defina o que faz o {idol} ser diferente de outros artistas na mesma posição que ele.",
        "Anote em qual momento exato da sua vida a música do {idol} encaixou como uma luva.",
        "Registre a inspiração que o corre e o esforço do {idol} te dão no dia a dia.",
        "Escreva seus feels depois de ver um stage do {idol}... sem filtros, só deixe fluir.",
        "Anote o que sente ao ver como o {idol} agradece ao fandom de um jeito tão top.",
        "Veja em que parte você também cresceu enquanto acompanhava o growth do {idol}.",
        "Busque aquele momento onde o {idol} mostrou vulnerabilidade... isso é bravura real.",
        "Analise qual relação da sua vida a música do {idol} te faz lembrar agora.",
        "Escolha um traço da coragem do {idol} que você gostaria de ter também.",
        "Busque o verso das lyrics do {idol} que melhor descreve sua situação atual.",
        "Identifique o que o {idol} nunca abandonou e escreva o que você não pode soltar.",
        "Pense naquele momento em que você só quer chill e relax com a música do {idol}.",
        "Busque o assunto que deixa o {idol} mais felizão nas entrevistas dele.",
        "Escolha a frase que resume os valores core do {idol} e compare com os seus.",
        "Imagine o que o {idol} te diria se estivesse do seu lado agora mesmo.",
        "Busca qual traço da sua personalidade mais combina com a música do {idol}.",
        "Copie no seu diário a mensagem mais calorosa que o {idol} já dedicou pro fandom.",
        "Imagine como seria sua rotina diária se a música do {idol} não existisse.",
        "Lembre o que você estava fazendo na época mais difícil da carreira do {idol}.",
        "Ache uma mensagem positiva sobre o futuro nas lyrics do {idol} e guarde no cora hoje.",
        "Aprenda como o {idol} protege a própria energia e aplique isso em você.",
        "Imagine como a música do {idol} ressoa com a sua energia elemental {u_el}.",
        "Busque o momento onde o {idol} aceitou as próprias imperfeições... brutal!",
        "Registre o momento exato em que a música do {idol} te deu mais conforto.",
        "Busca em que seus sonhos se parecem com os sonhos que o {idol} tem.",
        "Conecte uma música de solidão ou saudade do {idol} con seus próprios feels.",
        "Adicione um toque da disciplina do {idol} na sua própria rotina diária hoje.",
        "Observe a expressão do {idol} logo após terminar um stage... pura emoção!",
        "Compare seus likes e dislikes com os do {idol} e busque o match perfeito.",
        "Mande pra um amigo aquela frase das lyrics do {idol} que fez um click total em você.",
        "Busca provas de que o {idol} não é mais só um ídolo, mas um artista de verdade.",
        "Veja como seus sentimentos como fã do {idol} evoluíram com o passar do tempo.",
        "Busque a frase do {idol} que te deixou pensando de forma mais profunda.",
        "Imagine como a energia elemental do {idol} preenche os vazios da sua.",
        "Registre se você já fez algo criativo inspirado pela arte do {idol}.",
        "Escreva qual lado da sua personalidade aparece quando você ouve o {idol}.",
        "Busca a pergunta de entrevista que o {idol} respondeu com mais cautela.",
        "Escreva um diário sobre a motivação que a energia Fire (火) do {idol} te dá.",
        "Busca o novo challenge que o {idol} começou com a energia Wood (木) dele.",
        "Escreva seus feels de hoje num diário enquanto ouve o som do {idol}.",
        "Busca o que o {idol} disse que mais espera dos fãs no futuro.",
        "Ache a frase mais sábia das letras escritas pelo próprio {idol}.",
        "Busque vídeos onde o {idol} cuida dos outros membros... vibes de parceria.",
        "Escreva quais ansiedades se acalmam quando você dá o play no {idol}.",
        "Busca o momento em que o {idol} cumpriu uma promessa que fez pra si mesmo.",
        "Aplique uma mensagem de mudança e desafio do {idol} na sua própria vida hoje.",
        "Escreva sobre a atitude do {idol} que te provou a sinceridade total dele.",
        "Relembre e escreva a emoção de quando ouviu o {idol} pela primeira vez.",
        "Imagine o conselho que o {idol} te daria hoje e escreva no seu diário.",
        "Busca em qual área da sua vida você quer ser firme como o Metal (金) do {idol}.",
        "Busque o momento em que o {idol} cumpriu uma promessa feita pros fãs.",
        "Relembre aquele primeiro momento em que a música do {idol} te emocionou real.",
        "Busca a pergunta de entrevista que o {idol} mais demorou pra responder.",
        "Escreva seus sentimentos mais profundos e honestos (vibe Water) no diário hoje.",
        "Busca a entrevista onde o {idol} menciona as pessoas a quem ele é grato.",
        "Identifique o instrumento ou melodia na música do {idol} que mais te acalma.",
        "Busca a entrevista onde o {idol} fala con mais honestidade sobre seus sonhos.",
        "Busca a música com a visão mais madura sobre o amor em toda a discografia do {idol}.",
        "Ache o momento em que o {idol} agiu com mais humildade e respeito.",
        "Sinta como a música do {idol} preenche sua energia elemental faltante.",
        "Busca como o {idol} se recuperou depois de uma falha ou decepção.",
        "Busca a área da sua vida onde quer avançar com passo firme (energia Earth) como o {idol}.",
        "Lembre do momento em que o {idol} se entregou 100% pelos fãs.",
        "Escreva se tem alguma música do {idol} que deu um estalo na sua vida.",
        "Escolha um traço da atitude de vida do {idol} que você adoraria copiar.",
        "Busca o track que mais bate com a sua própria vibração agora mesmo.",
        "Busca a razão pela qual o {idol} aguentou firme quando as coisas ficaram feias.",
        "Escreva o que de mais valioso você aprendeu vendo o growth do {idol}.",
        "Descubra qual música o {idol} acha que define ele melhor e anote.",
        "Busca a frase das lyrics do {idol} que faz sintonia com o seu elemento {u_el}.",
        "Busca o sonho que o {idol} quer realizar um dia e conecte com o seu.",
        "Imagine como a sua energia e a do {idol} se completam... escreva no diário."
    ]

    # PT Star Tasks - Energy (97)
    pt_energy = [
        "Pra sentir a energia do {idol}, veja a melhor performance dele e anote qual momento brilhou mais. Aura pura!",
        "Busque o growth story do {idol} e compare com a sua própria timeline de crescimento.",
        "Ouça a música que o {idol} indicou e termine hoje aquela tarefa que você estava enrolando. Corre real!",
        "Ache a parte do growth story do {idol} que mais combina com você e aplique no seu desafio de hoje.",
        "Sinta a Fire energy (火) do {idol} e tente algo novo hoje. Se joga!",
        "Ouça o gênero de música que o {idol} ama e descubra qual parte faz um click com você.",
        "Seja firme como o Metal (金) do {idol} e termine hoje uma tarefa com perfeição.",
        "Flua como a Water energy (水) do {idol} e escreva seus feels honestos no diário hoje.",
        "Receba a Wood growth energy (木) do {idol} e comece aquele novo hobby ou desafio hoje mesmo.",
        "Busque como o {idol} cuida da saúde e adapte pra sua rotina. Health is wealth!",
        "Crie seu próprio setlist ideal pra um show do {idol} e explique suas escolhas.",
        "Aprenda como o {idol} superou o slump dele e compare com o seu jeito de lidar com o estresse.",
        "Escolha o traço de energia do {idol} que você mais quer copiar e coloque em prática hoje.",
        "Faça uma pequena promessa com você mesmo hoje como a Earth energy (土) do {idol} e cumpra!",
        "Busque qual era o mindset do {idol} antes de um grande desafio nas entrevistas dele.",
        "Saia pra caminhar ou faça um exercício leve por 30 min ouvindo o flow do {idol}.",
        "Veja como o {idol} treinava pesado pro stage e aplique essa dedicação no seu trampo de hoje.",
        "Absorva o carisma Fire (火) do {idol} e aja com total confiança hoje.",
        "Use um acessório da cor da energia {i_el} do {idol} hoje pra atrair boas vibes.",
        "Siga o exemplo de disciplina do {idol}: faça um plano pra hoje e cumpra tudo.",
        "Prepare algo importante hoje com o mesmo cuidado que o {idol} prepara um stage.",
        "Trabalhe hoje com foco total usando a música do {idol} como trilha sonora.",
        "Recarregue as energias com a comida ou snack fav que o {idol} sempre comenta.",
        "Mexa o corpo seguindo os passos da coreo do {idol}... use como um alongamento.",
        "Tente o esporte ou atividade física que o {idol} curte pra dar um gás.",
        "Com a paixão Fire (火) do {idol}, dê o seu máximo hoje numa tarefa importante.",
        "Busque o que o {idol} repetiu mil vezes pra alcançar o goal dele e faça o mesmo hoje.",
        "Caminhe ou corra no ritmo da track mais agitada do {idol}.",
        "Teste uma das dicas de self-care que o {idol} recomendou pros fãs.",
        "Com a precisão Metal (金) do {idol}, termine algo hoje com um acabamento top.",
        "Observe a atitude do {idol} quando ele está aprendendo algo novo e imite.",
        "Coloque o som mais rápido do {idol} e dê um glow up no seu quarto arrumando tudo.",
        "Busque como o {idol} relaxa e tira o estresse e aplique no seu dia hoje.",
        "Mergulhe fundo em algo hoje com a energia Water (水) do {idol}.",
        "Aplique o pro-spirit que o {idol} mostra no set de gravação no seu próprio trampo hoje.",
        "Como la Wood energy (木) do {idol}, comece algo hoje pela primeira vez. Fresh start!",
        "Se o {idol} tem uma rotina de foco, busque e teste hoje mesmo.",
        "Comece sua manhã com a vibe lá no alto ouvindo sua música fav do {idol}.",
        "Passe a energia positiva que o {idol} dá pros fãs para alguém do seu lado hoje.",
        "Seja constante como a Earth energy (土) do {idol} e repita um hábito hoje sem falhar.",
        "Veja como o {idol} se protege de energias ruins e aplique pra cuidar da sua paz.",
        "Assista à performance mais dinâmica do {idol} e coloque o corpo pra mexer também.",
        "Veja como o {idol} entra no foco total e se concentre em uma coisa só hoje.",
        "Avalie seu nível de energia hoje de 1 a 10 enquanto ouve o som do {idol}.",
        "Assista ao conteúdo mais alegre do {idol} e deixe essa vibe iluminar seu dia.",
        "Aproveite pra aprender algo hoje com a paixão Fire (火) do {idol}.",
        "Se o {idol} tiene um ritual antes de entrar no palco, adapte pra sua rotina de início de dia.",
        "Dê o play na track mais destemida do {idol} e tire forças pra encarar o dia.",
        "Busque qual é a postura do {idol} quando ele encara algo que ainda não domina.",
        "Coma algo que represente a energia {i_el} do {idol} pra recarregar sua aura.",
        "Busque o projeto em que o {idol} mais se dedicou e compare com o seu próprio goal.",
        "Saia pra dar um rolê ou uma volta por aí ouvindo o flow do {idol}.",
        "Tente imitar o esforço que o {idol} faz pra manter o físico e a saúde sempre ok.",
        "Adapte-se aos imprevistos hoje com a fluidez Water (水) do {idol}.",
        "Não desista daquela tarefa chata hoje, assim como o {idol} não desistiu da coreo.",
        "Sinta o prazer de aprender algo novo com a Wood energy (木) do {idol}.",
        "Busque como o {idol} foca a energia antes de um show e aplique antes de algo importante.",
        "Coloque o som mais motivador do {idol} e dê o seu máximo por 30 minutos.",
        "Passe a vibe boa que você recebeu do {idol} dizendo algo positivo pra alguém hoje.",
        "Termine o seu dia de forma limpa e organizada como a energia Metal (金) do {idol}.",
        "Busque como o {idol} recarrega as pilhas no dia de folga dele e adapte pra você.",
        "Mantenha seu flow e foco hoje com a música do {idol} tocando de fundo.",
        "Use os pontos fortes da sua energia {i_el} hoje de forma consciente como o {idol}.",
        "Aplique hoje algo do estilo goal-oriented de vida que o {idol} leva.",
        "Use a música mais hype do {idol} como o seu despertador pra acordar hoje.",
        "Prepare seu compromisso de hoje com o mesmo capricho que o {idol} se prepara pros fãs.",
        "Deixe suas emoções fluírem de leve hoje como a Water energy (水) do {idol}.",
        "Busque um exemplo de profissionalismo total do {idol} em qualquer situação.",
        "Anote suas ideias livremente hoje com a inspiração Wood (木) do {idol}.",
        "Aguente o momento mais treta do dia ouvindo o power do {idol}.",
        "Ache o segredo do {idol} pra manter a vitalidade lá em cima nas entrevistas.",
        "Dê estabilidade pra quem está do seu lado hoje como a Earth energy (土) do {idol}.",
        "Não desista do que você queria: termine essa tarefa com a Fire energy (火) do {idol}.",
        "Se o {idol} fala algo pra si mesmo antes de começar, use você também hoje.",
        "Defina sua meta de hoje em uma frase só ouvindo o som do {idol}.",
        "Busque o período em que o {idol} trabalhou sem parar e foque você também essa semana.",
        "Fale e aja com precisão hoje como a Metal energy (金) do {idol}.",
        "Busca como o {idol} expressa a energia dele e ache seu próprio jeito de se expressar.",
        "Imagine o power que surge quando a sua energia {u_el} se junta com a do {idol}.",
        "Se o {idol} tem um truque pra quando perde o foco, busque e use hoje mesmo.",
        "Veja a performance com mais power do {idol} e avalie seu nível de energia.",
        "Viva hoje com a maior vitalidade seguindo a Wood energy (木) do {idol}.",
        "Busque por que o {idol} não economiza energia nenhuma quando está no palco.",
        "Coloque a track com mais vibe de energia como a sua primeira música do dia.",
        "Busque como o {idol} se cuida quando a energia dele está no limite.",
        "Diga algo que alegre o ambiente ao seu redor com a Fire energy (火) do {idol}.",
        "Busque o método de recuperação do {idol} pós-show e aplique no seu descanso.",
        "Ajuste seus planos hoje com a flexibilidade da Water energy (水) do {idol}.",
        "Busque como o {idol} superou um momento de cansaço extremo e exaustão.",
        "Descanse 30 min totalmente curtindo o {idol} pra recarregar sua aura.",
        "Descubra em qual atividade o {idol} colocou mais energia em toda a carreira.",
        "Organize o que é bagunça e foque no importante hoje como a Metal energy (金) de {idol}.",
        "Mantenha seu próprio ritmo hoje sem perder o centro como a Earth energy (土) de {idol}.",
        "Coloque na sua rotina o jeito que o {idol} ganha nova energia todo dia.",
        "Imagine a sinergia brutal entre a sua energia {u_el} e a do {idol}.",
        "Analise como o {idol} usa a energia dele de forma eficiente durante as promos.",
        "Assista ao stage mais intenso do {idol} e suba um nível da sua própria vitalidade hoje."
    ]

    bundle = {
        "es": {
            "star_tasks": {
                "vibe": es_vibe,
                "heart": es_heart,
                "energy": es_energy
            }
        },
        "pt": {
            "star_tasks": {
                "vibe": pt_vibe,
                "heart": pt_heart,
                "energy": pt_energy
            }
        }
    }

    with open('star_tasks_bundle.json', 'w', encoding='utf-8') as f:
        json.dump(bundle, f, ensure_ascii=False, indent=4)
        print("Generated star_tasks_bundle.json successfully.")

if __name__ == "__main__":
    generate()
